[package]
name = "vela_mir"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
serde = [
  "dep:serde",
  "vela_common/serde",
  "vela_def/serde",
  "vela_hir/serde",
  "vela_package/serde",
]
test-support = []

[dependencies]
serde = { workspace = true, optional = true }
vela_analysis = { workspace = true }
vela_common = { workspace = true }
vela_def = { workspace = true }
vela_hir = { workspace = true }
vela_package = { workspace = true }

[lints]
workspace = true
