[package]
name = "vela_mir"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
test-support = []

[dependencies]
vela_analysis = { workspace = true }
vela_common = { workspace = true }
vela_def = { workspace = true }
vela_hir = { workspace = true }
vela_package = { workspace = true }

[lints]
workspace = true
