[package]
name = "vela_hir"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true, optional = true }
vela_common = { workspace = true }
vela_def = { workspace = true }
vela_package = { workspace = true }
vela_syntax = { workspace = true }

[features]
serde = [
  "dep:serde",
  "vela_common/serde",
  "vela_def/serde",
  "vela_package/serde",
]

[lints]
workspace = true
