"use strict";

const fs = require("node:fs");
const path = require("node:path");
const { spawnSync } = require("node:child_process");
const model = require("./model");
const { capabilities } = require("./stdio");
const { provenance } = require("./provenance");

const root = path.resolve(__dirname, "../..");
const output = path.join(root, "target/lsp-matrix");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");

function cargo(args, log) {
  console.log(`cargo ${args.join(" ")}`);
  const result = spawnSync("cargo", args, {
    cwd: root, encoding: "utf8", timeout: 300000, maxBuffer: 32 * 1024 * 1024, windowsHide: true,
    env: { ...process.env, CARGO_TERM_COLOR: "never" }
  });
  fs.writeFileSync(path.join(output, log), (result.stdout || "") + (result.stderr || ""));
  if (result.error) throw result.error;
  return result;
}

function markdown(report) {
  const lines = ["# LSP coverage audit", "",
    "Generated by `node scripts/lsp-matrix/run.js`. Candidate counts are discovery aids, not coverage proof.", "",
    `Test command failure: ${report.testCommandFailed ? "yes (acceptance failed)" : "no"}.`, "",
    `Grammar productions: ${report.grammarProductions}. Protocol rows: ${report.features.length}.`,
    `Requirements: ${report.requirements.length}. ${Object.entries(report.counts).map(([key, value]) => `${key}: ${value}`).join(", ")}.`, "",
    "Mapped = reviewed test linkage, not executed in this audit. Verified = all linked assertions passed in this invocation.",
    "Unreviewed = no complete proof mapped; existing tests may already cover part or all of the requirement.", "",
    "| Feature | Requirements | Verified | Mapped | Unreviewed | N/A | Candidate service / protocol tests |",
    "|---|---:|---:|---:|---:|---:|---:|"];
  for (const feature of report.features) {
    const requirements = report.requirements.filter((item) => item.feature === feature.id);
    const count = (status) => requirements.filter((item) => item.status === status).length;
    lines.push(`| ${feature.id} | ${requirements.length} | ${count("verified")} | ${count("mapped")} | ${count("unreviewed")} | ${count("not_applicable")} | ${feature.candidates.service.length} / ${feature.candidates.protocol.length} |`);
  }
  lines.push("", "## Next audit priorities", "",
    "1. All outgoing UTF-16 ranges, semantic-token lengths/deltas, and edits, including cross-file target text.",
    "2. Match every syntax dimension's positive and negative contract to specific assertions; split broad obligations before closing them.",
    "3. Saved/dirty/close/reopen and dependency create/change/delete sequences against a fresh-workspace oracle.",
    "4. Static host schema origins, stale/missing schema, returned receivers, and dynamic boundaries.",
    "5. Every advertised editor feature through installed VSIX; scheduled environment and scale sweeps.", "",
    "The full machine-readable obligation list, candidate test names, assertions, and capability snapshot are in report.json.",
    "Strict acceptance requires zero unreviewed, mapped-only, or failed obligations. Ordinary CI checks catalog integrity and test failures; it does not claim full acceptance.");
  return lines.join("\n") + "\n";
}

async function main() {
  const args = process.argv.slice(2);
  let editorResults;
  for (let index = 0; index < args.length; index++) {
    const arg = args[index];
    if (arg === "--editor-results") {
      editorResults = args[++index];
      if (!editorResults) throw new Error("--editor-results requires a results.json path");
    } else if (!["--run", "--strict"].includes(arg)) {
      throw new Error(`unknown option ${arg}; use --run, --strict, --editor-results <path>`);
    }
  }
  fs.mkdirSync(output, { recursive: true });
  const catalog = JSON.parse(read("tests/lsp_matrix/catalog.json"));
  catalog.protocolBaseline = JSON.parse(read("tests/lsp_matrix/protocol-baseline.json"));
  Object.assign(catalog, JSON.parse(read("tests/lsp_matrix/syntax-baseline.json")));
  catalog.features = catalog.featureFiles.flatMap((file) => {
    if (!/^features\/[a-z-]+\.json$/.test(file)) throw new Error(`invalid matrix feature file ${file}`);
    return JSON.parse(read(`tests/lsp_matrix/${file}`));
  });
  const requirements = model.validateCatalog(catalog, {
    protocol: read("docs/lsp-protocol-test-matrix.md"), grammar: read("docs/grammar.ebnf"),
    syntax: Object.fromEntries(Object.keys(catalog.syntaxSources).map((file) => [file, read(file)]))
  });
  const available = {};
  const results = {};
  let failed = false;
  for (const [layer, crate] of Object.entries({ service: "vela_language_service", protocol: "vela_lsp_server" })) {
    const listed = cargo(["test", "-p", crate, "--lib", "--", "--list"], `${layer}-list.log`);
    if (listed.status !== 0) throw new Error(`${crate} test discovery failed; see ${output}`);
    available[layer] = model.testNames(listed.stdout);
    if (!available[layer].length) throw new Error(`${crate}: no tests discovered`);
    if (args.includes("--run")) {
      const executed = cargo(["test", "-p", crate, "--lib", "--", "--color", "never"], `${layer}-run.log`);
      results[layer] = model.testResults(executed.stdout);
      failed ||= executed.status !== 0;
    }
  }
  available.editor = [...read("editors/vscode/test/suite.js").matchAll(/await check\("([^"]+)"/g)].map((match) => match[1]);
  const built = cargo(["build", "-p", "vela_lsp_server"], "build.log");
  if (built.status !== 0) throw new Error(`LSP build failed; see ${output}`);
  const metadata = cargo(["metadata", "--no-deps", "--format-version", "1"], "metadata.log");
  if (metadata.status !== 0) throw new Error("cargo metadata failed");
  const target = JSON.parse(metadata.stdout).target_directory;
  const binary = path.join(target, "debug", process.platform === "win32" ? "vela_lsp_server.exe" : "vela_lsp_server");
  const actualCapabilities = await capabilities(binary);
  if (editorResults) {
    const editor = JSON.parse(fs.readFileSync(path.resolve(editorResults), "utf8"));
    if (editor.version !== 1 || JSON.stringify(editor.provenance) !== JSON.stringify(provenance(root, binary))) {
      throw new Error("editor evidence is stale or from different sources/binary/platform; run npm test again");
    }
    if (!Array.isArray(editor.results) || new Set(editor.results.map((test) => test.name)).size !== editor.results.length) {
      throw new Error("invalid or duplicate editor test results");
    }
    results.editor = new Map(editor.results.map((test) => {
      if (!available.editor.includes(test.name)) throw new Error(`unknown editor result ${test.name}`);
      return [test.name, test.passed === true ? "ok" : "FAILED"];
    }));
    failed ||= editor.results.some((test) => test.passed !== true);
  }
  const keys = Object.keys(actualCapabilities).sort();
  if (JSON.stringify(keys) !== JSON.stringify(catalog.capabilityKeys)) {
    throw new Error(`advertised capability keys changed; update matrix applicability: ${keys.join(", ")}`);
  }
  const assessed = model.assess(requirements, catalog.evidence, available, results, catalog.exemptions);
  const features = catalog.features.map((feature) => ({ ...feature,
    contract: catalog.protocolBaseline[feature.row],
    candidates: Object.fromEntries(["service", "protocol"].map((layer) => [layer,
      available[layer].filter((test) => feature.candidatePrefixes[layer].some((prefix) => test.startsWith(prefix)))
    ]))
  }));
  const report = { version: 1, generatedAt: new Date().toISOString(), platform: process.platform,
    testCommandFailed: failed,
    executionRequested: args.includes("--run"), grammarProductions: catalog.grammarRules.length,
    grammarGroups: catalog.grammarGroups, syntaxDimensions: catalog.syntaxDimensions,
    counts: Object.fromEntries(["verified", "mapped", "unreviewed", "failed", "not_applicable"].map((status) =>
      [status, assessed.filter((item) => item.status === status).length])),
    actualCapabilities, features, requirements: assessed };
  fs.writeFileSync(path.join(output, "report.json"), JSON.stringify(report, null, 2) + "\n");
  fs.writeFileSync(path.join(output, "report.md"), markdown(report));
  console.log(`${features.length} protocol rows; ${assessed.length} obligations: ${JSON.stringify(report.counts)}`);
  console.log(`Report: ${path.join(output, "report.md")}`);
  if (failed || report.counts.failed || (args.includes("--strict") && assessed.some((item) => !["verified", "not_applicable"].includes(item.status)))) {
    console.error("Matrix acceptance is incomplete or tests failed; see report and logs.");
    process.exitCode = 1;
  }
}

main().catch((error) => { console.error(error); process.exitCode = 1; });
