"use strict";

const fs = require("node:fs");
const path = require("node:path");
const { spawnSync } = require("node:child_process");
const model = require("./model");
const { validateManifest } = require("./execution");
const checkpointModel = require("./checkpoint");
const { sourceIdentity } = require("./source-identity");
const { runInfrastructure, assessInfrastructure } = require("./infrastructure");
const { capabilities } = require("./stdio");
const { provenance } = require("./provenance");
const { createAuditDirectory, writeReports } = require("./audit-files");

const root = path.resolve(__dirname, "../..");
const reportRoot = path.join(root, "target/lsp-matrix");
let output;
const failedCommands = [];
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");

function cargo(args, log) {
  console.log(`cargo ${args.join(" ")}`);
  const result = spawnSync("cargo", args, {
    cwd: root, encoding: "utf8", timeout: 300000, maxBuffer: 32 * 1024 * 1024, windowsHide: true,
    env: { ...process.env, CARGO_TERM_COLOR: "never" }
  });
  fs.writeFileSync(path.join(output, log), (result.stdout || "") + (result.stderr || ""));
  if (result.status !== 0) failedCommands.push({ command: `cargo ${args.join(" ")}`, exitCode: result.status, log });
  if (result.error) throw result.error;
  return result;
}

function markdown(report) {
  const lines = ["# LSP coverage audit", "",
    "Generated by `node scripts/lsp-matrix/run.js`. Candidate counts are discovery aids, not coverage proof.", "",
    `Test command failure: ${report.testCommandFailed ? "yes (acceptance failed)" : "no"}.`, "",
    `Grammar productions: ${report.grammarProductions}. Protocol rows: ${report.features.length}.`,
    `Requirements: ${report.requirements.length}. ${Object.entries(report.counts).map(([key, value]) => `${key}: ${value}`).join(", ")}.`, "",
    "Mapped = reviewed test linkage, not executed in this audit. Verified = all linked assertions passed in this invocation.",
    "Unreviewed = no complete proof mapped; existing tests may already cover part or all of the requirement.", "",
    `Local execution requirements: ${report.execution.requirements.length}; accepted batches: ${report.execution.acceptedBatches.join(", ") || "none"}; B16 deferred.`, "",
    "| Feature | Requirements | Verified | Mapped | Unreviewed | N/A | Candidate service / protocol tests |",
    "|---|---:|---:|---:|---:|---:|---:|"];
  for (const feature of report.features) {
    const requirements = report.requirements.filter((item) => item.feature === feature.id);
    const count = (status) => requirements.filter((item) => item.status === status).length;
    lines.push(`| ${feature.id} | ${requirements.length} | ${count("verified")} | ${count("mapped")} | ${count("unreviewed")} | ${count("not_applicable")} | ${feature.candidates.service.length} / ${feature.candidates.protocol.length} |`);
  }
  lines.push("", "## Next audit priorities", "",
    "1. All outgoing UTF-16 ranges, semantic-token lengths/deltas, and edits, including cross-file target text.",
    "2. Match every syntax dimension's positive and negative contract to specific assertions; split broad obligations before closing them.",
    "3. Saved/dirty/close/reopen and dependency create/change/delete sequences against a fresh-workspace oracle.",
    "4. Static host schema origins, stale/missing schema, returned receivers, and dynamic boundaries.",
    "5. Every advertised editor feature through installed VSIX; scheduled environment and scale sweeps.", "",
    "The full machine-readable obligation list, candidate test names, assertions, and capability snapshot are in report.json.",
    "Strict acceptance requires zero unreviewed, mapped-only, or failed obligations. Ordinary CI checks catalog integrity and test failures; it does not claim full acceptance.");
  return lines.join("\n") + "\n";
}

async function main() {
  const args = process.argv.slice(2);
  let editorResults;
  let selectedBatch;
  let reopen;
  let reason;
  for (let index = 0; index < args.length; index++) {
    const arg = args[index];
    if (arg === "--editor-results") {
      editorResults = args[++index];
      if (!editorResults) throw new Error("--editor-results requires a results.json path");
    } else if (["--batch", "--reopen", "--reason"].includes(arg)) {
      const value = args[++index];
      if (!value || value.startsWith("--")) throw new Error(`${arg} requires a value`);
      if (arg === "--batch") selectedBatch = value;
      else if (arg === "--reopen") reopen = value;
      else reason = value;
    } else if (!["--run", "--strict", "--accept"].includes(arg)) {
      throw new Error(`unknown option ${arg}; use --run, --strict, --batch <id>, --accept, --editor-results <path>, --reopen <id> --reason <text>`);
    }
  }
  if (selectedBatch && !checkpointModel.localOrder.includes(selectedBatch)) throw new Error("unknown or deferred batch selection");
  if (args.includes("--accept") && (!selectedBatch || !args.includes("--run"))) throw new Error("--accept requires --run and --batch");
  if (reopen && (selectedBatch || args.includes("--accept") || args.includes("--run") || args.includes("--strict"))) throw new Error("--reopen must be a separate checkpoint operation");
  output = createAuditDirectory(reportRoot);
  console.log(`Audit artifacts: ${output}`);
  const catalog = JSON.parse(read("tests/lsp_matrix/catalog.json"));
  catalog.protocolBaseline = JSON.parse(read("tests/lsp_matrix/protocol-baseline.json"));
  Object.assign(catalog, JSON.parse(read("tests/lsp_matrix/syntax-baseline.json")));
  catalog.features = catalog.featureFiles.flatMap((file) => {
    if (!/^features\/[a-z-]+\.json$/.test(file)) throw new Error(`invalid matrix feature file ${file}`);
    return JSON.parse(read(`tests/lsp_matrix/${file}`));
  });
  const requirements = model.validateCatalog(catalog, {
    protocol: read("docs/lsp-protocol-test-matrix.md"), grammar: read("docs/grammar.ebnf"),
    syntax: Object.fromEntries(Object.keys(catalog.syntaxSources).map((file) => [file, read(file)]))
  });
  const manifest = JSON.parse(read("tests/lsp_matrix/execution-manifest.json"));
  const interactions = JSON.parse(read("tests/lsp_matrix/interactions.json"));
  if (interactions.version !== 1) throw new Error("unsupported interaction inventory version");
  const executionRequirements = validateManifest(manifest,
    JSON.parse(read("tests/lsp_matrix/execution-baseline.json")), catalog, requirements,
    interactions.scenarios, { plan: read("docs/lsp-test-execution-plan.md"),
      interactions: read("docs/lsp-vscode-interaction-matrix.md") });
  const checkpointPath = path.join(root, "tests/lsp_matrix/checkpoint.json");
  let checkpoint = JSON.parse(fs.readFileSync(checkpointPath, "utf8"));
  if (reopen) {
    checkpoint = checkpointModel.reopenBatch(checkpoint, executionRequirements, reopen, reason);
    checkpointModel.validateCheckpoint(checkpoint, manifest, executionRequirements);
    fs.writeFileSync(checkpointPath, JSON.stringify(checkpoint, null, 2) + "\n");
    console.log(`Reopened ${reopen}; next task ${checkpoint.nextTask}.`);
    return;
  }
  checkpointModel.validateCheckpoint(checkpoint, manifest, executionRequirements);
  checkpointModel.validateExecutionProfile(checkpoint.profile,
    { platform: process.platform, arch: process.arch }, Boolean(selectedBatch) || args.includes("--strict"));
  const source = sourceIdentity(root);
  const infrastructure = runInfrastructure(root, output, args.includes("--run"));
  if (infrastructure.failed) failedCommands.push({ command: "node --test scripts/lsp-matrix/*.test.js", log: "infrastructure.log" });
  const gateEvidence = JSON.parse(read("tests/lsp_matrix/gate-evidence.json"));
  if (gateEvidence.version !== 1) throw new Error("unsupported gate evidence version");
  const available = {};
  const results = {};
  let failed = infrastructure.failed;
  for (const [layer, crate] of Object.entries({ service: "vela_language_service", protocol: "vela_lsp_server" })) {
    const listed = cargo(["test", "-p", crate, "--lib", "--", "--list"], `${layer}-list.log`);
    if (listed.status !== 0) throw new Error(`${crate} test discovery failed; see ${output}`);
    available[layer] = model.testNames(listed.stdout);
    if (!available[layer].length) throw new Error(`${crate}: no tests discovered`);
    if (args.includes("--run")) {
      const executed = cargo(["test", "-p", crate, "--lib", "--", "--color", "never"], `${layer}-run.log`);
      results[layer] = model.testResults(executed.stdout);
      failed ||= executed.status !== 0;
    }
  }
  available.editor = [...read("editors/vscode/test/suite.js").matchAll(/await check\("([^"]+)"/g)].map((match) => match[1]);
  const built = cargo(["build", "-p", "vela_lsp_server"], "build.log");
  if (built.status !== 0) throw new Error(`LSP build failed; see ${output}`);
  const metadata = cargo(["metadata", "--no-deps", "--format-version", "1"], "metadata.log");
  if (metadata.status !== 0) throw new Error("cargo metadata failed");
  const target = JSON.parse(metadata.stdout).target_directory;
  const binary = path.join(target, "debug", process.platform === "win32" ? "vela_lsp_server.exe" : "vela_lsp_server");
  const actualCapabilities = await capabilities(binary);
  if (editorResults) {
    const editor = JSON.parse(fs.readFileSync(path.resolve(editorResults), "utf8"));
    checkpointModel.validateExecutionProfile(checkpoint.profile,
      { platform: process.platform, arch: process.arch, vscodeVersion: editor.vscodeVersion },
      Boolean(selectedBatch) || args.includes("--strict"));
    if (editor.version !== 1 || JSON.stringify(editor.provenance) !== JSON.stringify(provenance(root, binary))) {
      throw new Error("editor evidence is stale or from different sources/binary/platform; run npm test again");
    }
    if (!Array.isArray(editor.results) || new Set(editor.results.map((test) => test.name)).size !== editor.results.length) {
      throw new Error("invalid or duplicate editor test results");
    }
    results.editor = new Map(editor.results.map((test) => {
      if (!available.editor.includes(test.name)) throw new Error(`unknown editor result ${test.name}`);
      return [test.name, test.passed === true ? "ok" : "FAILED"];
    }));
    failed ||= editor.results.some((test) => test.passed !== true);
  }
  const keys = Object.keys(actualCapabilities).sort();
  if (JSON.stringify(keys) !== JSON.stringify(catalog.capabilityKeys)) {
    throw new Error(`advertised capability keys changed; update matrix applicability: ${keys.join(", ")}`);
  }
  const assessed = model.assess(requirements, catalog.evidence, available, results, catalog.exemptions);
  const gates = assessInfrastructure(executionRequirements, gateEvidence.evidence, infrastructure, { available, results });
  const features = catalog.features.map((feature) => ({ ...feature,
    contract: catalog.protocolBaseline[feature.row],
    candidates: Object.fromEntries(["service", "protocol"].map((layer) => [layer,
      available[layer].filter((test) => feature.candidatePrefixes[layer].some((prefix) => test.startsWith(prefix)))
    ]))
  }));
  const report = { version: 1, generatedAt: new Date().toISOString(), platform: process.platform,
    source,
    failedCommands, artifactDirectory: path.relative(root, output),
    testCommandFailed: failed,
    executionRequested: args.includes("--run"), grammarProductions: catalog.grammarRules.length,
    grammarGroups: catalog.grammarGroups, syntaxDimensions: catalog.syntaxDimensions,
    counts: Object.fromEntries(["verified", "mapped", "unreviewed", "failed", "not_applicable"].map((status) =>
      [status, assessed.filter((item) => item.status === status).length])),
    actualCapabilities, features, requirements: assessed,
    execution: { version: manifest.version, scope: manifest.scope,
      acceptedBatches: checkpoint.acceptedBatches.map((batch) => batch.id),
      deferredBatches: manifest.batches.filter((batch) => batch.scope === "deferred").map((batch) => batch.id),
      requirements: executionRequirements.map((requirement) => ({ ...requirement,
        status: [...assessed, ...gates].find((item) => item.id === requirement.id)?.status ?? "unreviewed" })) } };
  if (sourceIdentity(root).treeSha256 !== source.treeSha256) throw new Error("source inputs changed during audit; rerun before acceptance");
  writeReports(reportRoot, output, report, markdown(report));
  console.log(`${features.length} protocol rows; ${assessed.length} obligations: ${JSON.stringify(report.counts)}`);
  console.log(`Report: ${path.join(output, "report.md")}`);
  console.log(`Local execution inventory: ${executionRequirements.length} obligations; B16 deferred.`);
  if (failed || report.execution.requirements.some((item) => item.status === "failed")) {
    console.error("Matrix acceptance is incomplete or tests failed; see report and logs.");
    process.exitCode = 1;
    return;
  }
  if (selectedBatch || args.includes("--strict")) {
    checkpointModel.gate(executionRequirements, report.execution.requirements, checkpoint,
      args.includes("--strict") ? "all" : selectedBatch, failed);
    console.log(`Strict ${args.includes("--strict") ? "local" : selectedBatch} acceptance passed.`);
  }
  if (args.includes("--accept")) {
    const validation = { source, profile: checkpoint.profile,
      artifacts: [path.relative(root, path.join(output, "report.json"))],
      commands: [{ command: `node scripts/lsp-matrix/run.js ${args.filter((arg) => arg !== "--accept").join(" ")}`, exitCode: 0 }] };
    checkpoint = checkpointModel.acceptBatch(checkpoint, manifest, executionRequirements,
      report.execution.requirements, selectedBatch, validation, failed);
    fs.writeFileSync(checkpointPath, JSON.stringify(checkpoint, null, 2) + "\n");
    console.log(`Recorded ${selectedBatch}; next task ${checkpoint.nextTask ?? "complete"}.`);
  }
}

main().catch((error) => { console.error(error); process.exitCode = 1; });
