use std::sync::OnceLock;

use vela_def::MethodId;

#[derive(Clone, Copy)]
pub(crate) struct StdMethodIds {
    pub(crate) string_len: MethodId,
    pub(crate) string_is_empty: MethodId,
    pub(crate) string_contains: MethodId,
    pub(crate) string_find: MethodId,
    pub(crate) string_starts_with: MethodId,
    pub(crate) string_ends_with: MethodId,
    pub(crate) string_strip_prefix: MethodId,
    pub(crate) string_strip_suffix: MethodId,
    pub(crate) string_to_upper: MethodId,
    pub(crate) string_to_lower: MethodId,
    pub(crate) string_trim: MethodId,
    pub(crate) string_trim_start: MethodId,
    pub(crate) string_trim_end: MethodId,
    pub(crate) string_replace: MethodId,
    pub(crate) string_repeat: MethodId,
    pub(crate) string_slice: MethodId,
    pub(crate) string_split: MethodId,
    pub(crate) string_split_once: MethodId,
    pub(crate) string_split_lines: MethodId,
    pub(crate) string_split_whitespace: MethodId,
    pub(crate) string_parse_int: MethodId,
    pub(crate) string_parse_float: MethodId,
    pub(crate) string_parse_bool: MethodId,
    pub(crate) bytes_len: MethodId,
    pub(crate) bytes_is_empty: MethodId,
    pub(crate) bytes_slice: MethodId,
    pub(crate) bytes_get: MethodId,
    pub(crate) bytes_read_u32_le: MethodId,
    pub(crate) bytes_read_u32_be: MethodId,
    pub(crate) bytes_to_hex: MethodId,
    pub(crate) array_len: MethodId,
    pub(crate) array_is_empty: MethodId,
    pub(crate) array_push: MethodId,
    pub(crate) array_pop: MethodId,
    pub(crate) array_insert: MethodId,
    pub(crate) array_extend: MethodId,
    pub(crate) array_clear: MethodId,
    pub(crate) array_first: MethodId,
    pub(crate) array_last: MethodId,
    pub(crate) array_remove_at: MethodId,
    pub(crate) array_join: MethodId,
    pub(crate) array_contains: MethodId,
    pub(crate) array_index_of: MethodId,
    pub(crate) array_distinct: MethodId,
    pub(crate) array_reverse: MethodId,
    pub(crate) array_slice: MethodId,
    pub(crate) array_sort: MethodId,
    pub(crate) array_min: MethodId,
    pub(crate) array_max: MethodId,
    pub(crate) array_sum: MethodId,
    pub(crate) map_len: MethodId,
    pub(crate) map_is_empty: MethodId,
    pub(crate) map_has: MethodId,
    pub(crate) map_get: MethodId,
    pub(crate) map_get_or: MethodId,
    pub(crate) map_set: MethodId,
    pub(crate) map_remove: MethodId,
    pub(crate) map_extend: MethodId,
    pub(crate) map_clear: MethodId,
    pub(crate) map_keys: MethodId,
    pub(crate) map_values: MethodId,
    pub(crate) map_entries: MethodId,
    pub(crate) map_merge: MethodId,
    pub(crate) set_len: MethodId,
    pub(crate) set_is_empty: MethodId,
    pub(crate) set_has: MethodId,
    pub(crate) set_add: MethodId,
    pub(crate) set_remove: MethodId,
    pub(crate) set_extend: MethodId,
    pub(crate) set_clear: MethodId,
    pub(crate) set_values: MethodId,
    pub(crate) set_union: MethodId,
    pub(crate) set_intersection: MethodId,
    pub(crate) set_difference: MethodId,
    pub(crate) set_symmetric_difference: MethodId,
    pub(crate) set_is_subset: MethodId,
    pub(crate) set_is_superset: MethodId,
    pub(crate) set_is_disjoint: MethodId,
    pub(crate) option_is_some: MethodId,
    pub(crate) option_is_none: MethodId,
    pub(crate) option_unwrap_or: MethodId,
    pub(crate) option_ok_or: MethodId,
    pub(crate) option_flatten: MethodId,
    pub(crate) result_is_ok: MethodId,
    pub(crate) result_is_err: MethodId,
    pub(crate) result_unwrap_or: MethodId,
    pub(crate) result_to_option: MethodId,
    pub(crate) result_to_error_option: MethodId,
    pub(crate) result_flatten: MethodId,
    pub(crate) range_len: MethodId,
    pub(crate) range_is_empty: MethodId,
}

impl StdMethodIds {
    fn new() -> Self {
        Self {
            string_len: standard_method_id("String", "len"),
            string_is_empty: standard_method_id("String", "is_empty"),
            string_contains: standard_method_id("String", "contains"),
            string_find: standard_method_id("String", "find"),
            string_starts_with: standard_method_id("String", "starts_with"),
            string_ends_with: standard_method_id("String", "ends_with"),
            string_strip_prefix: standard_method_id("String", "strip_prefix"),
            string_strip_suffix: standard_method_id("String", "strip_suffix"),
            string_to_upper: standard_method_id("String", "to_upper"),
            string_to_lower: standard_method_id("String", "to_lower"),
            string_trim: standard_method_id("String", "trim"),
            string_trim_start: standard_method_id("String", "trim_start"),
            string_trim_end: standard_method_id("String", "trim_end"),
            string_replace: standard_method_id("String", "replace"),
            string_repeat: standard_method_id("String", "repeat"),
            string_slice: standard_method_id("String", "slice"),
            string_split: standard_method_id("String", "split"),
            string_split_once: standard_method_id("String", "split_once"),
            string_split_lines: standard_method_id("String", "split_lines"),
            string_split_whitespace: standard_method_id("String", "split_whitespace"),
            string_parse_int: standard_method_id("String", "parse_int"),
            string_parse_float: standard_method_id("String", "parse_float"),
            string_parse_bool: standard_method_id("String", "parse_bool"),
            bytes_len: standard_method_id("Bytes", "len"),
            bytes_is_empty: standard_method_id("Bytes", "is_empty"),
            bytes_slice: standard_method_id("Bytes", "slice"),
            bytes_get: standard_method_id("Bytes", "get"),
            bytes_read_u32_le: standard_method_id("Bytes", "read_u32_le"),
            bytes_read_u32_be: standard_method_id("Bytes", "read_u32_be"),
            bytes_to_hex: standard_method_id("Bytes", "to_hex"),
            array_len: standard_method_id("Array", "len"),
            array_is_empty: standard_method_id("Array", "is_empty"),
            array_push: standard_method_id("Array", "push"),
            array_pop: standard_method_id("Array", "pop"),
            array_insert: standard_method_id("Array", "insert"),
            array_extend: standard_method_id("Array", "extend"),
            array_clear: standard_method_id("Array", "clear"),
            array_first: standard_method_id("Array", "first"),
            array_last: standard_method_id("Array", "last"),
            array_remove_at: standard_method_id("Array", "remove_at"),
            array_join: standard_method_id("Array", "join"),
            array_contains: standard_method_id("Array", "contains"),
            array_index_of: standard_method_id("Array", "index_of"),
            array_distinct: standard_method_id("Array", "distinct"),
            array_reverse: standard_method_id("Array", "reverse"),
            array_slice: standard_method_id("Array", "slice"),
            array_sort: standard_method_id("Array", "sort"),
            array_min: standard_method_id("Array", "min"),
            array_max: standard_method_id("Array", "max"),
            array_sum: standard_method_id("Array", "sum"),
            map_len: standard_method_id("Map", "len"),
            map_is_empty: standard_method_id("Map", "is_empty"),
            map_has: standard_method_id("Map", "has"),
            map_get: standard_method_id("Map", "get"),
            map_get_or: standard_method_id("Map", "get_or"),
            map_set: standard_method_id("Map", "set"),
            map_remove: standard_method_id("Map", "remove"),
            map_extend: standard_method_id("Map", "extend"),
            map_clear: standard_method_id("Map", "clear"),
            map_keys: standard_method_id("Map", "keys"),
            map_values: standard_method_id("Map", "values"),
            map_entries: standard_method_id("Map", "entries"),
            map_merge: standard_method_id("Map", "merge"),
            set_len: standard_method_id("Set", "len"),
            set_is_empty: standard_method_id("Set", "is_empty"),
            set_has: standard_method_id("Set", "has"),
            set_add: standard_method_id("Set", "add"),
            set_remove: standard_method_id("Set", "remove"),
            set_extend: standard_method_id("Set", "extend"),
            set_clear: standard_method_id("Set", "clear"),
            set_values: standard_method_id("Set", "values"),
            set_union: standard_method_id("Set", "union"),
            set_intersection: standard_method_id("Set", "intersection"),
            set_difference: standard_method_id("Set", "difference"),
            set_symmetric_difference: standard_method_id("Set", "symmetric_difference"),
            set_is_subset: standard_method_id("Set", "is_subset"),
            set_is_superset: standard_method_id("Set", "is_superset"),
            set_is_disjoint: standard_method_id("Set", "is_disjoint"),
            option_is_some: standard_method_id("Option", "is_some"),
            option_is_none: standard_method_id("Option", "is_none"),
            option_unwrap_or: standard_method_id("Option", "unwrap_or"),
            option_ok_or: standard_method_id("Option", "ok_or"),
            option_flatten: standard_method_id("Option", "flatten"),
            result_is_ok: standard_method_id("Result", "is_ok"),
            result_is_err: standard_method_id("Result", "is_err"),
            result_unwrap_or: standard_method_id("Result", "unwrap_or"),
            result_to_option: standard_method_id("Result", "to_option"),
            result_to_error_option: standard_method_id("Result", "to_error_option"),
            result_flatten: standard_method_id("Result", "flatten"),
            range_len: standard_method_id("Range", "len"),
            range_is_empty: standard_method_id("Range", "is_empty"),
        }
    }
}

pub(crate) fn std_method_ids() -> &'static StdMethodIds {
    static IDS: OnceLock<StdMethodIds> = OnceLock::new();
    IDS.get_or_init(StdMethodIds::new)
}

fn standard_method_id(owner: &str, name: &str) -> MethodId {
    let Some(id) = vela_stdlib::std_method_id(owner, name) else {
        panic!("missing standard method identity for {owner}::{name}");
    };
    id
}
