use crate::manifest::{StdMethodSpec, StdParamSpec};

pub const STD_METHODS: &[StdMethodSpec] = &[
    StdMethodSpec::new(
        "String",
        "len",
        &[],
        "i64",
        "Returns the string length in bytes.",
    ),
    StdMethodSpec::new(
        "String",
        "is_empty",
        &[],
        "bool",
        "Returns true when the string has no characters.",
    ),
    StdMethodSpec::new(
        "String",
        "contains",
        &[StdParamSpec::new("needle", "string")],
        "bool",
        "Returns true when the string contains the needle.",
    ),
    StdMethodSpec::new(
        "String",
        "find",
        &[StdParamSpec::new("needle", "string")],
        "Option",
        "Returns the byte index of the first match, or Option::None.",
    ),
    StdMethodSpec::new(
        "String",
        "starts_with",
        &[StdParamSpec::new("prefix", "string")],
        "bool",
        "Returns true when the string starts with the prefix.",
    ),
    StdMethodSpec::new(
        "String",
        "ends_with",
        &[StdParamSpec::new("suffix", "string")],
        "bool",
        "Returns true when the string ends with the suffix.",
    ),
    StdMethodSpec::new(
        "String",
        "strip_prefix",
        &[StdParamSpec::new("prefix", "string")],
        "Option",
        "Returns the string without the prefix, or Option::None.",
    ),
    StdMethodSpec::new(
        "String",
        "strip_suffix",
        &[StdParamSpec::new("suffix", "string")],
        "Option",
        "Returns the string without the suffix, or Option::None.",
    ),
    StdMethodSpec::new(
        "String",
        "to_upper",
        &[],
        "string",
        "Returns an uppercase copy.",
    ),
    StdMethodSpec::new(
        "String",
        "to_lower",
        &[],
        "string",
        "Returns a lowercase copy.",
    ),
    StdMethodSpec::new(
        "String",
        "trim",
        &[],
        "string",
        "Returns a copy with leading and trailing whitespace removed.",
    ),
    StdMethodSpec::new(
        "String",
        "trim_start",
        &[],
        "string",
        "Returns a copy with leading whitespace removed.",
    ),
    StdMethodSpec::new(
        "String",
        "trim_end",
        &[],
        "string",
        "Returns a copy with trailing whitespace removed.",
    ),
    StdMethodSpec::new(
        "String",
        "replace",
        &[
            StdParamSpec::new("old", "string"),
            StdParamSpec::new("new", "string"),
        ],
        "string",
        "Returns a copy with all matches replaced.",
    ),
    StdMethodSpec::new(
        "String",
        "repeat",
        &[StdParamSpec::new("count", "i64")],
        "string",
        "Returns the string repeated count times.",
    ),
    StdMethodSpec::new(
        "String",
        "slice",
        &[
            StdParamSpec::new("start", "i64"),
            StdParamSpec::new("end", "i64"),
        ],
        "string",
        "Returns the substring in the byte range.",
    ),
    StdMethodSpec::new(
        "String",
        "split",
        &[StdParamSpec::new("separator", "string")],
        "array",
        "Returns string segments split by the separator.",
    ),
    StdMethodSpec::new(
        "String",
        "split_once",
        &[StdParamSpec::new("separator", "string")],
        "Option",
        "Returns the first split pair, or Option::None.",
    ),
    StdMethodSpec::new(
        "String",
        "split_lines",
        &[],
        "array",
        "Returns the string split into lines.",
    ),
    StdMethodSpec::new(
        "String",
        "split_whitespace",
        &[],
        "array",
        "Returns the string split on whitespace.",
    ),
    StdMethodSpec::new(
        "String",
        "parse_i8",
        &[],
        "Option",
        "Parses the string as an i8, or Option::None.",
    ),
    StdMethodSpec::new(
        "String",
        "parse_i16",
        &[],
        "Option",
        "Parses the string as an i16, or Option::None.",
    ),
    StdMethodSpec::new(
        "String",
        "parse_i32",
        &[],
        "Option",
        "Parses the string as an i32, or Option::None.",
    ),
    StdMethodSpec::new(
        "String",
        "parse_i64",
        &[],
        "Option",
        "Parses the string as an i64, or Option::None.",
    ),
    StdMethodSpec::new(
        "String",
        "parse_u8",
        &[],
        "Option",
        "Parses the string as a u8, or Option::None.",
    ),
    StdMethodSpec::new(
        "String",
        "parse_u16",
        &[],
        "Option",
        "Parses the string as a u16, or Option::None.",
    ),
    StdMethodSpec::new(
        "String",
        "parse_u32",
        &[],
        "Option",
        "Parses the string as a u32, or Option::None.",
    ),
    StdMethodSpec::new(
        "String",
        "parse_u64",
        &[],
        "Option",
        "Parses the string as a u64, or Option::None.",
    ),
    StdMethodSpec::new(
        "String",
        "parse_f32",
        &[],
        "Option",
        "Parses the string as a finite f32, or Option::None.",
    ),
    StdMethodSpec::new(
        "String",
        "parse_f64",
        &[],
        "Option",
        "Parses the string as a finite f64, or Option::None.",
    ),
    StdMethodSpec::new(
        "String",
        "parse_bool",
        &[],
        "Option",
        "Parses the string as a boolean, or Option::None.",
    ),
    StdMethodSpec::new(
        "String",
        "parse_char",
        &[],
        "Option",
        "Parses the string as a single char, or Option::None.",
    ),
    StdMethodSpec::new(
        "String",
        "chars",
        &[],
        "iterator",
        "Returns a character iterator over the string.",
    ),
    StdMethodSpec::new(
        "String",
        "bytes",
        &[],
        "iterator",
        "Returns a UTF-8 byte iterator over the string.",
    ),
    StdMethodSpec::new("Bytes", "len", &[], "i64", "Returns the byte length."),
    StdMethodSpec::new(
        "Bytes",
        "is_empty",
        &[],
        "bool",
        "Returns true when the byte buffer has no bytes.",
    ),
    StdMethodSpec::new(
        "Bytes",
        "slice",
        &[
            StdParamSpec::new("start", "i64"),
            StdParamSpec::new("end", "i64"),
        ],
        "bytes",
        "Returns the byte range as a new byte buffer.",
    ),
    StdMethodSpec::new(
        "Bytes",
        "get",
        &[StdParamSpec::new("index", "i64")],
        "u8",
        "Returns the byte at the index.",
    ),
    StdMethodSpec::new(
        "Bytes",
        "read_u32_le",
        &[StdParamSpec::new("index", "i64")],
        "u32",
        "Reads four bytes at the index as little-endian u32.",
    ),
    StdMethodSpec::new(
        "Bytes",
        "read_u32_be",
        &[StdParamSpec::new("index", "i64")],
        "u32",
        "Reads four bytes at the index as big-endian u32.",
    ),
    StdMethodSpec::new(
        "Bytes",
        "to_hex",
        &[],
        "string",
        "Returns the lowercase hexadecimal representation.",
    ),
    StdMethodSpec::new(
        "Bytes",
        "iter",
        &[],
        "iterator",
        "Returns a byte iterator over the byte buffer.",
    ),
    StdMethodSpec::new(
        "Bytes",
        "values",
        &[],
        "iterator",
        "Returns a byte iterator over the byte buffer.",
    ),
    StdMethodSpec::new(
        "Char",
        "to_string",
        &[],
        "string",
        "Returns the character as a string.",
    ),
    StdMethodSpec::new(
        "Char",
        "is_whitespace",
        &[],
        "bool",
        "Returns true when the character is whitespace.",
    ),
    StdMethodSpec::new(
        "Char",
        "is_ascii",
        &[],
        "bool",
        "Returns true when the character is ASCII.",
    ),
    StdMethodSpec::new(
        "Char",
        "is_ascii_digit",
        &[],
        "bool",
        "Returns true when the character is an ASCII decimal digit.",
    ),
    StdMethodSpec::new("Array", "len", &[], "i64", "Returns the array length."),
    StdMethodSpec::new(
        "Array",
        "is_empty",
        &[],
        "bool",
        "Returns true when the array has no elements.",
    ),
    StdMethodSpec::new(
        "Array",
        "push",
        &[StdParamSpec::new("value", "any")],
        "null",
        "Appends a value to the array.",
    ),
    StdMethodSpec::new(
        "Array",
        "pop",
        &[],
        "Option",
        "Removes and returns the last value.",
    ),
    StdMethodSpec::new(
        "Array",
        "insert",
        &[
            StdParamSpec::new("index", "i64"),
            StdParamSpec::new("value", "any"),
        ],
        "null",
        "Inserts a value at an index.",
    ),
    StdMethodSpec::new(
        "Array",
        "extend",
        &[StdParamSpec::new("values", "array")],
        "null",
        "Appends all values from another array.",
    ),
    StdMethodSpec::new("Array", "clear", &[], "null", "Removes all values."),
    StdMethodSpec::new("Array", "first", &[], "Option", "Returns the first value."),
    StdMethodSpec::new("Array", "last", &[], "Option", "Returns the last value."),
    StdMethodSpec::new(
        "Array",
        "remove_at",
        &[StdParamSpec::new("index", "i64")],
        "Option",
        "Removes and returns the value at an index.",
    ),
    StdMethodSpec::new(
        "Array",
        "join",
        &[StdParamSpec::new("separator", "string")],
        "string",
        "Joins values into a string with a separator.",
    ),
    StdMethodSpec::new(
        "Array",
        "contains",
        &[StdParamSpec::new("value", "any")],
        "bool",
        "Returns true when the array contains a value.",
    ),
    StdMethodSpec::new(
        "Array",
        "index_of",
        &[StdParamSpec::new("value", "any")],
        "Option",
        "Returns the first index of a value, or Option::None.",
    ),
    StdMethodSpec::new("Array", "distinct", &[], "array", "Returns unique values."),
    StdMethodSpec::new(
        "Array",
        "reverse",
        &[],
        "array",
        "Returns values in reverse order.",
    ),
    StdMethodSpec::new(
        "Array",
        "slice",
        &[
            StdParamSpec::new("start", "i64"),
            StdParamSpec::new("end", "i64"),
        ],
        "array",
        "Returns values in the index range.",
    ),
    StdMethodSpec::new(
        "Array",
        "map",
        &[StdParamSpec::new("callback", "function")],
        "array",
        "Maps each value with a callback.",
    ),
    StdMethodSpec::new(
        "Array",
        "filter",
        &[StdParamSpec::new("callback", "function")],
        "array",
        "Keeps values accepted by a callback.",
    ),
    StdMethodSpec::new(
        "Array",
        "find",
        &[StdParamSpec::new("callback", "function")],
        "Option",
        "Returns the first callback match, or Option::None.",
    ),
    StdMethodSpec::new(
        "Array",
        "any",
        &[StdParamSpec::new("callback", "function")],
        "bool",
        "Returns true when any value matches a callback.",
    ),
    StdMethodSpec::new(
        "Array",
        "all",
        &[StdParamSpec::new("callback", "function")],
        "bool",
        "Returns true when all values match a callback.",
    ),
    StdMethodSpec::new(
        "Array",
        "count",
        &[StdParamSpec::new("callback", "function")],
        "i64",
        "Counts values accepted by a callback.",
    ),
    StdMethodSpec::new(
        "Array",
        "sum",
        &[StdParamSpec::optional("callback", "function")],
        "any",
        "Sums values or callback results.",
    ),
    StdMethodSpec::new(
        "Array",
        "group_by",
        &[StdParamSpec::new("callback", "function")],
        "map",
        "Groups values by value-keyed callback keys.",
    ),
    StdMethodSpec::new("Array", "sort", &[], "array", "Returns sorted values."),
    StdMethodSpec::new("Array", "min", &[], "Option", "Returns the minimum value."),
    StdMethodSpec::new("Array", "max", &[], "Option", "Returns the maximum value."),
    StdMethodSpec::new(
        "Array",
        "sort_by",
        &[StdParamSpec::new("callback", "function")],
        "array",
        "Returns values sorted by callback keys.",
    ),
    StdMethodSpec::new(
        "Array",
        "iter",
        &[],
        "iterator",
        "Returns a one-shot iterator over array values.",
    ),
    StdMethodSpec::new(
        "Array",
        "values",
        &[],
        "iterator",
        "Returns a one-shot iterator over array values.",
    ),
    StdMethodSpec::new("Map", "len", &[], "i64", "Returns the map length."),
    StdMethodSpec::new(
        "Map",
        "is_empty",
        &[],
        "bool",
        "Returns true when the map has no entries.",
    ),
    StdMethodSpec::new(
        "Map",
        "has",
        &[StdParamSpec::new("key", "any")],
        "bool",
        "Returns true when a key exists.",
    ),
    StdMethodSpec::new(
        "Map",
        "get",
        &[StdParamSpec::new("key", "any")],
        "Option",
        "Returns the value for a key, or Option::None.",
    ),
    StdMethodSpec::new(
        "Map",
        "get_or",
        &[
            StdParamSpec::new("key", "any"),
            StdParamSpec::new("default", "any"),
        ],
        "any",
        "Returns the value for a key or a default.",
    ),
    StdMethodSpec::new(
        "Map",
        "set",
        &[
            StdParamSpec::new("key", "any"),
            StdParamSpec::new("value", "any"),
        ],
        "any",
        "Sets and returns a value for a key.",
    ),
    StdMethodSpec::new(
        "Map",
        "remove",
        &[StdParamSpec::new("key", "any")],
        "Option",
        "Removes and returns the value for a key.",
    ),
    StdMethodSpec::new(
        "Map",
        "extend",
        &[StdParamSpec::new("values", "map")],
        "null",
        "Inserts entries from another map.",
    ),
    StdMethodSpec::new("Map", "clear", &[], "null", "Removes all entries."),
    StdMethodSpec::new(
        "Map",
        "keys",
        &[],
        "iterator",
        "Returns keys in sorted order.",
    ),
    StdMethodSpec::new(
        "Map",
        "values",
        &[],
        "iterator",
        "Returns values in key order.",
    ),
    StdMethodSpec::new(
        "Map",
        "entries",
        &[],
        "iterator",
        "Returns key/value records.",
    ),
    StdMethodSpec::new(
        "Map",
        "merge",
        &[StdParamSpec::new("other", "map")],
        "map",
        "Returns a merged map.",
    ),
    StdMethodSpec::new(
        "Map",
        "map_values",
        &[StdParamSpec::new("callback", "function")],
        "map",
        "Maps values with a callback.",
    ),
    StdMethodSpec::new(
        "Map",
        "filter",
        &[StdParamSpec::new("callback", "function")],
        "map",
        "Keeps entries accepted by a callback.",
    ),
    StdMethodSpec::new(
        "Map",
        "find",
        &[StdParamSpec::new("callback", "function")],
        "Option",
        "Returns the first matching entry, or Option::None.",
    ),
    StdMethodSpec::new(
        "Map",
        "any",
        &[StdParamSpec::new("callback", "function")],
        "bool",
        "Returns true when any entry matches a callback.",
    ),
    StdMethodSpec::new(
        "Map",
        "all",
        &[StdParamSpec::new("callback", "function")],
        "bool",
        "Returns true when all entries match a callback.",
    ),
    StdMethodSpec::new(
        "Map",
        "count",
        &[StdParamSpec::new("callback", "function")],
        "i64",
        "Counts entries accepted by a callback.",
    ),
    StdMethodSpec::new(
        "Map",
        "iter",
        &[],
        "iterator",
        "Returns a one-shot iterator over map values in key order.",
    ),
    StdMethodSpec::new("Set", "len", &[], "i64", "Returns the set length."),
    StdMethodSpec::new(
        "Set",
        "is_empty",
        &[],
        "bool",
        "Returns true when the set has no values.",
    ),
    StdMethodSpec::new(
        "Set",
        "has",
        &[StdParamSpec::new("value", "any")],
        "bool",
        "Returns true when a value exists.",
    ),
    StdMethodSpec::new(
        "Set",
        "add",
        &[StdParamSpec::new("value", "any")],
        "bool",
        "Adds a value and returns whether it was new.",
    ),
    StdMethodSpec::new(
        "Set",
        "remove",
        &[StdParamSpec::new("value", "any")],
        "bool",
        "Removes a value and returns whether it existed.",
    ),
    StdMethodSpec::new(
        "Set",
        "extend",
        &[StdParamSpec::new("values", "set")],
        "null",
        "Adds all values from another set.",
    ),
    StdMethodSpec::new("Set", "clear", &[], "null", "Removes all values."),
    StdMethodSpec::new(
        "Set",
        "values",
        &[],
        "iterator",
        "Returns a one-shot iterator over set values.",
    ),
    StdMethodSpec::new(
        "Set",
        "map",
        &[StdParamSpec::new("callback", "function")],
        "set",
        "Maps values with a callback.",
    ),
    StdMethodSpec::new(
        "Set",
        "filter",
        &[StdParamSpec::new("callback", "function")],
        "set",
        "Keeps values accepted by a callback.",
    ),
    StdMethodSpec::new(
        "Set",
        "find",
        &[StdParamSpec::new("callback", "function")],
        "Option",
        "Returns the first callback match, or Option::None.",
    ),
    StdMethodSpec::new(
        "Set",
        "any",
        &[StdParamSpec::new("callback", "function")],
        "bool",
        "Returns true when any value matches a callback.",
    ),
    StdMethodSpec::new(
        "Set",
        "all",
        &[StdParamSpec::new("callback", "function")],
        "bool",
        "Returns true when all values match a callback.",
    ),
    StdMethodSpec::new(
        "Set",
        "count",
        &[StdParamSpec::new("callback", "function")],
        "i64",
        "Counts values accepted by a callback.",
    ),
    StdMethodSpec::new(
        "Set",
        "union",
        &[StdParamSpec::new("other", "set")],
        "set",
        "Returns the union of two sets.",
    ),
    StdMethodSpec::new(
        "Set",
        "intersection",
        &[StdParamSpec::new("other", "set")],
        "set",
        "Returns shared values between two sets.",
    ),
    StdMethodSpec::new(
        "Set",
        "difference",
        &[StdParamSpec::new("other", "set")],
        "set",
        "Returns values missing from the other set.",
    ),
    StdMethodSpec::new(
        "Set",
        "symmetric_difference",
        &[StdParamSpec::new("other", "set")],
        "set",
        "Returns values present in exactly one set.",
    ),
    StdMethodSpec::new(
        "Set",
        "is_subset",
        &[StdParamSpec::new("other", "set")],
        "bool",
        "Returns true when all values exist in another set.",
    ),
    StdMethodSpec::new(
        "Set",
        "is_superset",
        &[StdParamSpec::new("other", "set")],
        "bool",
        "Returns true when all other values exist in this set.",
    ),
    StdMethodSpec::new(
        "Set",
        "is_disjoint",
        &[StdParamSpec::new("other", "set")],
        "bool",
        "Returns true when two sets share no values.",
    ),
    StdMethodSpec::new(
        "Set",
        "iter",
        &[],
        "iterator",
        "Returns a one-shot iterator over set values.",
    ),
    StdMethodSpec::new(
        "Option",
        "is_some",
        &[],
        "bool",
        "Returns true when the option contains a value.",
    ),
    StdMethodSpec::new(
        "Option",
        "is_none",
        &[],
        "bool",
        "Returns true when the option is empty.",
    ),
    StdMethodSpec::new(
        "Option",
        "unwrap_or",
        &[StdParamSpec::new("default", "any")],
        "any",
        "Returns the contained value or a default.",
    ),
    StdMethodSpec::new(
        "Option",
        "ok_or",
        &[StdParamSpec::new("error", "any")],
        "Result",
        "Converts Option::None to Result::Err with an error value.",
    ),
    StdMethodSpec::new(
        "Option",
        "flatten",
        &[],
        "Option",
        "Flattens a nested dynamic Option value.",
    ),
    StdMethodSpec::new(
        "Option",
        "map",
        &[StdParamSpec::new("callback", "function")],
        "Option",
        "Maps an Option::Some payload with a callback.",
    ),
    StdMethodSpec::new(
        "Option",
        "and_then",
        &[StdParamSpec::new("callback", "function")],
        "Option",
        "Chains an Option::Some payload through an Option-returning callback.",
    ),
    StdMethodSpec::new(
        "Option",
        "or_else",
        &[StdParamSpec::new("callback", "function")],
        "Option",
        "Calls a fallback callback when the option is empty.",
    ),
    StdMethodSpec::new(
        "Option",
        "filter",
        &[StdParamSpec::new("predicate", "function")],
        "Option",
        "Keeps an Option::Some payload accepted by a predicate.",
    ),
    StdMethodSpec::new(
        "Result",
        "is_ok",
        &[],
        "bool",
        "Returns true when the result contains a success value.",
    ),
    StdMethodSpec::new(
        "Result",
        "is_err",
        &[],
        "bool",
        "Returns true when the result contains an error value.",
    ),
    StdMethodSpec::new(
        "Result",
        "unwrap_or",
        &[StdParamSpec::new("default", "any")],
        "any",
        "Returns the success value or a default.",
    ),
    StdMethodSpec::new(
        "Result",
        "to_option",
        &[],
        "Option",
        "Converts Result::Ok to Option::Some and Result::Err to Option::None.",
    ),
    StdMethodSpec::new(
        "Result",
        "to_error_option",
        &[],
        "Option",
        "Converts Result::Err to Option::Some and Result::Ok to Option::None.",
    ),
    StdMethodSpec::new(
        "Result",
        "flatten",
        &[],
        "Result",
        "Flattens a nested dynamic Result value.",
    ),
    StdMethodSpec::new(
        "Result",
        "map",
        &[StdParamSpec::new("callback", "function")],
        "Result",
        "Maps a Result::Ok payload with a callback.",
    ),
    StdMethodSpec::new(
        "Result",
        "map_err",
        &[StdParamSpec::new("callback", "function")],
        "Result",
        "Maps a Result::Err payload with a callback.",
    ),
    StdMethodSpec::new(
        "Result",
        "and_then",
        &[StdParamSpec::new("callback", "function")],
        "Result",
        "Chains a Result::Ok payload through a Result-returning callback.",
    ),
    StdMethodSpec::new(
        "Result",
        "or_else",
        &[StdParamSpec::new("callback", "function")],
        "Result",
        "Calls an error-aware fallback callback for Result::Err.",
    ),
    StdMethodSpec::new("Range", "len", &[], "i64", "Returns the range length."),
    StdMethodSpec::new(
        "Range",
        "is_empty",
        &[],
        "bool",
        "Returns true when the range contains no values.",
    ),
    StdMethodSpec::new(
        "Range",
        "iter",
        &[],
        "iterator",
        "Returns a one-shot iterator over range values.",
    ),
    StdMethodSpec::new(
        "Iterator",
        "next",
        &[],
        "Option",
        "Advances the iterator and returns the next value.",
    ),
    StdMethodSpec::new(
        "Iterator",
        "count",
        &[],
        "i64",
        "Consumes the iterator and returns the remaining item count.",
    ),
    StdMethodSpec::new(
        "Iterator",
        "any",
        &[StdParamSpec::new("callback", "function")],
        "bool",
        "Consumes the iterator until a callback returns true.",
    ),
    StdMethodSpec::new(
        "Iterator",
        "all",
        &[StdParamSpec::new("callback", "function")],
        "bool",
        "Consumes the iterator until a callback returns false.",
    ),
    StdMethodSpec::new(
        "Iterator",
        "find",
        &[StdParamSpec::new("callback", "function")],
        "Option",
        "Consumes the iterator until a callback returns true.",
    ),
    StdMethodSpec::new(
        "Iterator",
        "map",
        &[StdParamSpec::new("callback", "function")],
        "iterator",
        "Returns a lazy iterator that maps each value through a callback.",
    ),
    StdMethodSpec::new(
        "Iterator",
        "filter",
        &[StdParamSpec::new("callback", "function")],
        "iterator",
        "Returns a lazy iterator that yields values accepted by a callback.",
    ),
    StdMethodSpec::new(
        "Iterator",
        "take",
        &[StdParamSpec::new("count", "i64")],
        "iterator",
        "Returns a lazy iterator over at most count remaining values.",
    ),
    StdMethodSpec::new(
        "Iterator",
        "skip",
        &[StdParamSpec::new("count", "i64")],
        "iterator",
        "Returns a lazy iterator after skipping count remaining values.",
    ),
    StdMethodSpec::new(
        "Iterator",
        "collect_array",
        &[],
        "array",
        "Consumes the iterator and collects remaining values into an array.",
    ),
    StdMethodSpec::new(
        "Iterator",
        "collect_set",
        &[],
        "set",
        "Consumes the iterator and collects remaining unique value-keyed values into a set.",
    ),
    StdMethodSpec::new(
        "Iterator",
        "collect_map",
        &[],
        "map",
        "Consumes MapEntry values and collects them into a map.",
    ),
];
