use vela_common::stable_id;
use vela_def::{FieldId, TypeId, VariantId};

pub use vela_common::standard_ids::{
    ARRAY_CLEAR_METHOD_ID, ARRAY_CONTAINS_METHOD_ID, ARRAY_DISTINCT_METHOD_ID,
    ARRAY_FIRST_METHOD_ID, ARRAY_INDEX_OF_METHOD_ID, ARRAY_IS_EMPTY_METHOD_ID,
    ARRAY_JOIN_METHOD_ID, ARRAY_LAST_METHOD_ID, ARRAY_LEN_METHOD_ID, ARRAY_POP_METHOD_ID,
    ARRAY_PUSH_METHOD_ID, ARRAY_REVERSE_METHOD_ID, ARRAY_SLICE_METHOD_ID, MAP_CLEAR_METHOD_ID,
    MAP_HAS_METHOD_ID, MAP_IS_EMPTY_METHOD_ID, MAP_LEN_METHOD_ID, MAP_REMOVE_METHOD_ID,
    MAP_SET_METHOD_ID, MATH_ABS_FUNCTION_ID, MATH_CEIL_FUNCTION_ID, MATH_CLAMP_FUNCTION_ID,
    MATH_DISTANCE2D_FUNCTION_ID, MATH_DISTANCE3D_FUNCTION_ID, MATH_FLOOR_FUNCTION_ID,
    MATH_LERP_FUNCTION_ID, MATH_MAX_FUNCTION_ID, MATH_MIN_FUNCTION_ID,
    MATH_MOVE_TOWARDS_FUNCTION_ID, MATH_POW_FUNCTION_ID, MATH_ROUND_FUNCTION_ID,
    MATH_SIGN_FUNCTION_ID, MATH_SQRT_FUNCTION_ID, OPTION_FLATTEN_FUNCTION_ID,
    OPTION_IS_NONE_FUNCTION_ID, OPTION_IS_NONE_METHOD_ID, OPTION_IS_SOME_FUNCTION_ID,
    OPTION_IS_SOME_METHOD_ID, OPTION_NONE_FUNCTION_ID, OPTION_OK_OR_FUNCTION_ID,
    OPTION_SOME_FUNCTION_ID, OPTION_UNWRAP_OR_FUNCTION_ID, RANGE_IS_EMPTY_METHOD_ID,
    RANGE_LEN_METHOD_ID, RESULT_ERR_FUNCTION_ID, RESULT_FLATTEN_FUNCTION_ID,
    RESULT_IS_ERR_FUNCTION_ID, RESULT_IS_ERR_METHOD_ID, RESULT_IS_OK_FUNCTION_ID,
    RESULT_IS_OK_METHOD_ID, RESULT_OK_FUNCTION_ID, RESULT_TO_ERROR_OPTION_FUNCTION_ID,
    RESULT_TO_OPTION_FUNCTION_ID, RESULT_UNWRAP_OR_FUNCTION_ID, SET_ADD_METHOD_ID,
    SET_CLEAR_METHOD_ID, SET_FROM_ARRAY_FUNCTION_ID, SET_HAS_METHOD_ID, SET_IS_DISJOINT_METHOD_ID,
    SET_IS_EMPTY_METHOD_ID, SET_IS_SUBSET_METHOD_ID, SET_IS_SUPERSET_METHOD_ID, SET_LEN_METHOD_ID,
    SET_REMOVE_METHOD_ID, STRING_CHAR_AT_METHOD_ID, STRING_CONTAINS_METHOD_ID,
    STRING_ENDS_WITH_METHOD_ID, STRING_FIND_METHOD_ID, STRING_IS_EMPTY_METHOD_ID,
    STRING_LEN_METHOD_ID, STRING_PARSE_BOOL_METHOD_ID, STRING_PARSE_FLOAT_METHOD_ID,
    STRING_PARSE_INT_METHOD_ID, STRING_REPEAT_METHOD_ID, STRING_REPLACE_METHOD_ID,
    STRING_SLICE_METHOD_ID, STRING_SPLIT_LINES_METHOD_ID, STRING_SPLIT_METHOD_ID,
    STRING_SPLIT_ONCE_METHOD_ID, STRING_SPLIT_WHITESPACE_METHOD_ID, STRING_STARTS_WITH_METHOD_ID,
    STRING_STRIP_PREFIX_METHOD_ID, STRING_STRIP_SUFFIX_METHOD_ID, STRING_TO_LOWER_METHOD_ID,
    STRING_TO_UPPER_METHOD_ID, STRING_TRIM_END_METHOD_ID, STRING_TRIM_METHOD_ID,
    STRING_TRIM_START_METHOD_ID,
};

const fn std_type(name: &str) -> TypeId {
    TypeId::new(stable_id("std_type", "", name) as u128)
}

const fn std_variant(owner: &str, name: &str) -> VariantId {
    VariantId::new(stable_id("std_variant", owner, name) as u128)
}

const fn std_field(owner: &str, name: &str) -> FieldId {
    FieldId::new(stable_id("std_field", owner, name) as u128)
}

pub const NULL_TYPE_ID: TypeId = std_type("Null");
pub const BOOL_TYPE_ID: TypeId = std_type("Bool");
pub const INT_TYPE_ID: TypeId = std_type("Int");
pub const FLOAT_TYPE_ID: TypeId = std_type("Float");
pub const STRING_TYPE_ID: TypeId = std_type("String");
pub const ARRAY_TYPE_ID: TypeId = std_type("Array");
pub const MAP_TYPE_ID: TypeId = std_type("Map");
pub const SET_TYPE_ID: TypeId = std_type("Set");
pub const FUNCTION_TYPE_ID: TypeId = std_type("Function");
pub const CLOSURE_TYPE_ID: TypeId = std_type("Closure");
pub const RANGE_TYPE_ID: TypeId = std_type("Range");
pub const OPTION_TYPE_ID: TypeId = std_type("Option");
pub const RESULT_TYPE_ID: TypeId = std_type("Result");

pub(crate) const OPTION_SOME_VARIANT_ID: VariantId = std_variant("Option", "Some");
pub(crate) const OPTION_NONE_VARIANT_ID: VariantId = std_variant("Option", "None");
pub(crate) const RESULT_OK_VARIANT_ID: VariantId = std_variant("Result", "Ok");
pub(crate) const RESULT_ERR_VARIANT_ID: VariantId = std_variant("Result", "Err");
pub(crate) const OPTION_SOME_FIELD_ID: FieldId = std_field("Option::Some", "0");
pub(crate) const RESULT_OK_FIELD_ID: FieldId = std_field("Result::Ok", "0");
pub(crate) const RESULT_ERR_FIELD_ID: FieldId = std_field("Result::Err", "0");
