mod functions;
mod ids;
mod methods;
mod modules;
mod types;

pub use ids::{
    ARRAY_CLEAR_METHOD_ID, ARRAY_CONTAINS_METHOD_ID, ARRAY_FIRST_METHOD_ID,
    ARRAY_INDEX_OF_METHOD_ID, ARRAY_IS_EMPTY_METHOD_ID, ARRAY_LAST_METHOD_ID, ARRAY_LEN_METHOD_ID,
    ARRAY_POP_METHOD_ID, ARRAY_PUSH_METHOD_ID, ARRAY_TYPE_ID, BOOL_TYPE_ID, CLOSURE_TYPE_ID,
    FLOAT_TYPE_ID, FUNCTION_TYPE_ID, INT_TYPE_ID, MAP_CLEAR_METHOD_ID, MAP_HAS_METHOD_ID,
    MAP_IS_EMPTY_METHOD_ID, MAP_LEN_METHOD_ID, MAP_REMOVE_METHOD_ID, MAP_SET_METHOD_ID,
    MAP_TYPE_ID, MATH_ABS_FUNCTION_ID, MATH_CEIL_FUNCTION_ID, MATH_CLAMP_FUNCTION_ID,
    MATH_DISTANCE2D_FUNCTION_ID, MATH_DISTANCE3D_FUNCTION_ID, MATH_FLOOR_FUNCTION_ID,
    MATH_LERP_FUNCTION_ID, MATH_MAX_FUNCTION_ID, MATH_MIN_FUNCTION_ID,
    MATH_MOVE_TOWARDS_FUNCTION_ID, MATH_POW_FUNCTION_ID, MATH_ROUND_FUNCTION_ID,
    MATH_SIGN_FUNCTION_ID, MATH_SQRT_FUNCTION_ID, NULL_TYPE_ID, OPTION_FLATTEN_FUNCTION_ID,
    OPTION_IS_NONE_FUNCTION_ID, OPTION_IS_NONE_METHOD_ID, OPTION_IS_SOME_FUNCTION_ID,
    OPTION_IS_SOME_METHOD_ID, OPTION_NONE_FUNCTION_ID, OPTION_OK_OR_FUNCTION_ID,
    OPTION_SOME_FUNCTION_ID, OPTION_TYPE_ID, OPTION_UNWRAP_OR_FUNCTION_ID,
    RANGE_IS_EMPTY_METHOD_ID, RANGE_LEN_METHOD_ID, RANGE_TYPE_ID, RESULT_ERR_FUNCTION_ID,
    RESULT_FLATTEN_FUNCTION_ID, RESULT_IS_ERR_FUNCTION_ID, RESULT_IS_ERR_METHOD_ID,
    RESULT_IS_OK_FUNCTION_ID, RESULT_IS_OK_METHOD_ID, RESULT_OK_FUNCTION_ID,
    RESULT_TO_ERROR_OPTION_FUNCTION_ID, RESULT_TO_OPTION_FUNCTION_ID, RESULT_TYPE_ID,
    RESULT_UNWRAP_OR_FUNCTION_ID, SET_ADD_METHOD_ID, SET_CLEAR_METHOD_ID,
    SET_FROM_ARRAY_FUNCTION_ID, SET_HAS_METHOD_ID, SET_IS_DISJOINT_METHOD_ID,
    SET_IS_EMPTY_METHOD_ID, SET_IS_SUBSET_METHOD_ID, SET_IS_SUPERSET_METHOD_ID, SET_LEN_METHOD_ID,
    SET_REMOVE_METHOD_ID, SET_TYPE_ID, STRING_CHAR_AT_METHOD_ID, STRING_CONTAINS_METHOD_ID,
    STRING_ENDS_WITH_METHOD_ID, STRING_FIND_METHOD_ID, STRING_IS_EMPTY_METHOD_ID,
    STRING_LEN_METHOD_ID, STRING_PARSE_BOOL_METHOD_ID, STRING_PARSE_FLOAT_METHOD_ID,
    STRING_PARSE_INT_METHOD_ID, STRING_REPEAT_METHOD_ID, STRING_REPLACE_METHOD_ID,
    STRING_SLICE_METHOD_ID, STRING_SPLIT_LINES_METHOD_ID, STRING_SPLIT_METHOD_ID,
    STRING_SPLIT_ONCE_METHOD_ID, STRING_SPLIT_WHITESPACE_METHOD_ID, STRING_STARTS_WITH_METHOD_ID,
    STRING_STRIP_PREFIX_METHOD_ID, STRING_STRIP_SUFFIX_METHOD_ID, STRING_TO_LOWER_METHOD_ID,
    STRING_TO_UPPER_METHOD_ID, STRING_TRIM_END_METHOD_ID, STRING_TRIM_METHOD_ID,
    STRING_TRIM_START_METHOD_ID, STRING_TYPE_ID,
};

pub(crate) use functions::standard_native_function_descs;
pub(crate) use modules::standard_module_descs;
pub(crate) use types::standard_type_descs;
