mod functions;
mod ids;
mod types;

pub use ids::{
    ARRAY_TYPE_ID, BOOL_TYPE_ID, CLOSURE_TYPE_ID, FLOAT_TYPE_ID, FUNCTION_TYPE_ID, INT_TYPE_ID,
    MAP_TYPE_ID, MATH_ABS_FUNCTION_ID, MATH_CEIL_FUNCTION_ID, MATH_CLAMP_FUNCTION_ID,
    MATH_DISTANCE2D_FUNCTION_ID, MATH_DISTANCE3D_FUNCTION_ID, MATH_FLOOR_FUNCTION_ID,
    MATH_LERP_FUNCTION_ID, MATH_MAX_FUNCTION_ID, MATH_MIN_FUNCTION_ID,
    MATH_MOVE_TOWARDS_FUNCTION_ID, MATH_POW_FUNCTION_ID, MATH_ROUND_FUNCTION_ID,
    MATH_SIGN_FUNCTION_ID, MATH_SQRT_FUNCTION_ID, NULL_TYPE_ID, OPTION_FLATTEN_FUNCTION_ID,
    OPTION_IS_NONE_FUNCTION_ID, OPTION_IS_SOME_FUNCTION_ID, OPTION_NONE_FUNCTION_ID,
    OPTION_OK_OR_FUNCTION_ID, OPTION_SOME_FUNCTION_ID, OPTION_TYPE_ID,
    OPTION_UNWRAP_OR_FUNCTION_ID, RESULT_ERR_FUNCTION_ID, RESULT_FLATTEN_FUNCTION_ID,
    RESULT_IS_ERR_FUNCTION_ID, RESULT_IS_OK_FUNCTION_ID, RESULT_OK_FUNCTION_ID,
    RESULT_TO_ERROR_OPTION_FUNCTION_ID, RESULT_TO_OPTION_FUNCTION_ID, RESULT_TYPE_ID,
    RESULT_UNWRAP_OR_FUNCTION_ID, SET_FROM_ARRAY_FUNCTION_ID, SET_TYPE_ID, STRING_TYPE_ID,
};

pub(crate) use functions::standard_native_function_descs;
pub(crate) use types::standard_type_descs;
