use std::collections::BTreeSet;
use std::fmt::{self, Write};

use vela_bytecode::{
    RUST_BINDING_SCHEMA_VERSION, RustBindingCallable, RustBindingCallableIdentity,
    RustBindingModule, RustBindingSchema, RustBindingType,
};
use vela_common::Span;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RustBindingGeneratorOptions {
    pub module_name: String,
}

impl Default for RustBindingGeneratorOptions {
    fn default() -> Self {
        Self {
            module_name: "vela_bindings".to_owned(),
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedRustBindings {
    pub code: String,
    pub schema_version: u32,
    pub schema_checksum: u64,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RustBindingDiagnostic {
    pub code: &'static str,
    pub message: String,
    pub source: Option<Span>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RustBindingGenerationError {
    diagnostics: Box<[RustBindingDiagnostic]>,
}

impl RustBindingGenerationError {
    #[must_use]
    pub fn diagnostics(&self) -> &[RustBindingDiagnostic] {
        &self.diagnostics
    }
}

impl fmt::Display for RustBindingGenerationError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "Rust binding generation failed with {} diagnostic(s)",
            self.diagnostics.len()
        )
    }
}

impl std::error::Error for RustBindingGenerationError {}

pub fn generate_rust_bindings(
    schema: &RustBindingSchema,
    options: &RustBindingGeneratorOptions,
) -> Result<GeneratedRustBindings, RustBindingGenerationError> {
    let mut diagnostics = Vec::new();
    if schema.version() != RUST_BINDING_SCHEMA_VERSION {
        diagnostics.push(RustBindingDiagnostic {
            code: "bindgen::unsupported_schema_version",
            message: format!(
                "binding schema version {} is not supported; expected {}",
                schema.version(),
                RUST_BINDING_SCHEMA_VERSION
            ),
            source: None,
        });
    }
    let module_name = rust_identifier(&options.module_name, NameStyle::Snake).ok_or_else(|| {
        generation_error(RustBindingDiagnostic {
            code: "bindgen::invalid_module_name",
            message: format!(
                "`{}` cannot be represented as a Rust module",
                options.module_name
            ),
            source: None,
        })
    })?;
    let modules = collect_modules(schema, &mut diagnostics);
    if !diagnostics.is_empty() {
        return Err(RustBindingGenerationError {
            diagnostics: diagnostics.into_boxed_slice(),
        });
    }

    let mut code = String::new();
    writeln!(code, "// @generated by vela_bindgen; do not edit.").expect("writing to String");
    writeln!(
        code,
        "// Vela binding schema v{} checksum {:016x}.",
        schema.version(),
        schema.checksum()
    )
    .expect("writing to String");
    writeln!(code, "#[allow(clippy::all, dead_code)]").expect("writing to String");
    writeln!(code, "pub mod {module_name} {{").expect("writing to String");
    writeln!(
        code,
        "    pub const SCHEMA_VERSION: u32 = {};",
        schema.version()
    )
    .expect("writing to String");
    writeln!(
        code,
        "    pub const SCHEMA_CHECKSUM: u64 = 0x{:016x};",
        schema.checksum()
    )
    .expect("writing to String");
    render_specs(&mut code, &modules, schema);
    render_package(&mut code, &modules);
    for module in &modules {
        render_module(&mut code, module);
    }
    writeln!(code, "}}").expect("writing to String");

    Ok(GeneratedRustBindings {
        code,
        schema_version: schema.version(),
        schema_checksum: schema.checksum(),
    })
}

struct GeneratedModule<'schema> {
    rust_name: String,
    accessor_name: String,
    source_name: String,
    callables: Vec<GeneratedCallable<'schema>>,
}

struct GeneratedCallable<'schema> {
    schema_index: usize,
    constant_name: String,
    rust_name: String,
    callable: &'schema RustBindingCallable,
    parameter_types: Vec<String>,
    return_type: String,
}

fn collect_modules<'schema>(
    schema: &'schema RustBindingSchema,
    diagnostics: &mut Vec<RustBindingDiagnostic>,
) -> Vec<GeneratedModule<'schema>> {
    let mut modules = Vec::new();
    let mut module_names = BTreeSet::new();
    for package in schema.packages() {
        for module in &package.modules {
            let source_name = module_source_name(package.id.as_str(), module);
            let Some(rust_name) = rust_identifier(&source_name, NameStyle::Snake) else {
                diagnostics.push(RustBindingDiagnostic {
                    code: "bindgen::invalid_module_path",
                    message: format!("`{source_name}` cannot be represented as a Rust module"),
                    source: module.callables.first().map(|callable| callable.source),
                });
                continue;
            };
            if !module_names.insert(rust_name.clone()) {
                diagnostics.push(RustBindingDiagnostic {
                    code: "bindgen::module_name_collision",
                    message: format!(
                        "Vela module `{source_name}` collides with another generated Rust module `{rust_name}`"
                    ),
                    source: module.callables.first().map(|callable| callable.source),
                });
                continue;
            }
            let mut method_names = BTreeSet::new();
            let mut callables = Vec::new();
            for (index, callable) in module.callables.iter().enumerate() {
                let Some(callable_name) = rust_identifier(&callable.rust_name, NameStyle::Snake)
                else {
                    diagnostics.push(RustBindingDiagnostic {
                        code: "bindgen::invalid_callable_name",
                        message: format!(
                            "Vela callable `{}` cannot be represented as a Rust method",
                            callable.public_path
                        ),
                        source: Some(callable.source),
                    });
                    continue;
                };
                if !method_names.insert(callable_name.clone()) {
                    diagnostics.push(RustBindingDiagnostic {
                        code: "bindgen::callable_name_collision",
                        message: format!(
                            "Vela callable `{}` collides with generated Rust method `{callable_name}`",
                            callable.public_path
                        ),
                        source: Some(callable.source),
                    });
                    continue;
                }
                let parameter_types = callable
                    .parameters
                    .iter()
                    .map(|parameter| render_type(&parameter.ty, parameter.source, diagnostics))
                    .collect::<Vec<_>>();
                let return_type = render_type(&callable.returns.ty, callable.source, diagnostics);
                callables.push(GeneratedCallable {
                    schema_index: 0,
                    constant_name: format!(
                        "CALLABLE_{}_{index}",
                        plain_identifier(&callable_name).to_ascii_uppercase()
                    ),
                    rust_name: callable_name,
                    callable,
                    parameter_types,
                    return_type,
                });
            }
            modules.push(GeneratedModule {
                accessor_name: format!("{rust_name}_module"),
                rust_name,
                source_name,
                callables,
            });
        }
    }
    modules.sort_by(|left, right| left.source_name.cmp(&right.source_name));
    for (schema_index, callable) in modules
        .iter_mut()
        .flat_map(|module| module.callables.iter_mut())
        .enumerate()
    {
        callable.schema_index = schema_index;
    }
    modules
}

fn module_source_name(package: &str, module: &RustBindingModule) -> String {
    let package = if package.is_empty() || package == "<anonymous>" {
        "anonymous"
    } else {
        package
    };
    let path = module.path.join();
    if path.is_empty() {
        format!("{package}_root")
    } else {
        format!("{package}_{path}")
    }
}

fn render_specs(output: &mut String, modules: &[GeneratedModule<'_>], schema: &RustBindingSchema) {
    writeln!(
        output,
        "    pub static SCHEMA: ::vela_engine::binding::BindingSchemaSpec = ::vela_engine::binding::BindingSchemaSpec::new(SCHEMA_VERSION, SCHEMA_CHECKSUM, &[")
    .expect("writing to String");
    for module in modules {
        for generated in &module.callables {
            let callable = generated.callable;
            let constructor = match callable.identity {
                RustBindingCallableIdentity::Function(function) => format!(
                    "::vela_engine::binding::BindingCallableSpec::function(0x{:032x}, 0x{:032x}, 0x{:016x}, {}, {}, {}, {})",
                    function.get(),
                    callable.executable.get(),
                    callable.contract_fingerprint,
                    callable.effects.bits(),
                    callable.source.source.get(),
                    callable.source.start,
                    callable.source.end
                ),
                RustBindingCallableIdentity::Method { owner, method } => format!(
                    "::vela_engine::binding::BindingCallableSpec::method(0x{:032x}, 0x{:032x}, 0x{:032x}, 0x{:016x}, {}, {}, {}, {})",
                    owner.get(),
                    method.get(),
                    callable.executable.get(),
                    callable.contract_fingerprint,
                    callable.effects.bits(),
                    callable.source.source.get(),
                    callable.source.start,
                    callable.source.end
                ),
            };
            writeln!(output, "        {constructor},").expect("writing to String");
        }
    }
    writeln!(output, "    ]);").expect("writing to String");
    let _ = schema;
}

fn render_package(output: &mut String, modules: &[GeneratedModule<'_>]) {
    writeln!(output, "    pub struct Package<A> {{ authority: A }}").expect("writing to String");
    writeln!(
        output,
        "    pub fn bind(runtime: &mut ::vela_engine::runtime::Runtime) -> ::vela_engine::binding::VmResult<Package<::vela_engine::binding::RootBinding<'_>>> {{"
    )
    .expect("writing to String");
    writeln!(
        output,
        "        Ok(Package {{ authority: ::vela_engine::binding::RootBinding::bind(runtime, &SCHEMA)? }})"
    )
    .expect("writing to String");
    writeln!(output, "    }}").expect("writing to String");
    writeln!(
        output,
        "    pub fn bind_active<'ctx, 'host>(context: &'ctx mut ::vela_engine::NativeCallContext<'_, 'host>) -> ::vela_engine::binding::VmResult<Package<::vela_engine::binding::ActiveBinding<'ctx, 'host>>> {{"
    )
    .expect("writing to String");
    writeln!(
        output,
        "        Ok(Package {{ authority: ::vela_engine::binding::ActiveBinding::bind(context, &SCHEMA)? }})"
    )
    .expect("writing to String");
    writeln!(output, "    }}").expect("writing to String");
    writeln!(
        output,
        "    impl<A: ::vela_engine::binding::BindingAuthority> Package<A> {{"
    )
    .expect("writing to String");
    for module in modules {
        writeln!(
            output,
            "        pub fn {}(&mut self) -> {}::Module<'_, A> {{ {}::Module {{ authority: &mut self.authority }} }}",
            module.accessor_name, module.rust_name, module.rust_name
        )
        .expect("writing to String");
    }
    writeln!(output, "    }}").expect("writing to String");
}

fn render_module(output: &mut String, module: &GeneratedModule<'_>) {
    writeln!(output, "    pub mod {} {{", module.rust_name).expect("writing to String");
    writeln!(
        output,
        "        pub struct Module<'a, A> {{ pub(super) authority: &'a mut A }}"
    )
    .expect("writing to String");
    for generated in &module.callables {
        writeln!(
            output,
            "        const {}: ::vela_engine::binding::BindingCallable = ::vela_engine::binding::BindingCallable::new(&super::SCHEMA, {});",
            generated.constant_name, generated.schema_index
        )
        .expect("writing to String");
    }
    writeln!(
        output,
        "        impl<'a, A: ::vela_engine::binding::BindingAuthority> Module<'a, A> {{"
    )
    .expect("writing to String");
    for generated in &module.callables {
        render_callable(output, generated);
    }
    writeln!(output, "        }}").expect("writing to String");
    writeln!(output, "    }}").expect("writing to String");
}

fn render_callable(output: &mut String, generated: &GeneratedCallable<'_>) {
    let callable = generated.callable;
    if let Some(docs) = &callable.docs {
        for line in docs.lines() {
            writeln!(output, "            #[doc = {:?}]", line).expect("writing to String");
        }
    }
    writeln!(
        output,
        "            #[doc = {:?}]",
        format!(
            "Vela source {}:{}..{}; contract {:016x}.",
            callable.source.source.get(),
            callable.source.start,
            callable.source.end,
            callable.contract_fingerprint
        )
    )
    .expect("writing to String");
    let parameters = generated
        .parameter_types
        .iter()
        .zip(&callable.parameters)
        .map(|(ty, parameter)| {
            let name = rust_identifier(&parameter.name, NameStyle::Snake)
                .unwrap_or_else(|| "invalid_parameter".to_owned());
            format!("{name}: {ty}")
        })
        .collect::<Vec<_>>()
        .join(", ");
    let arguments = callable
        .parameters
        .iter()
        .map(|parameter| {
            rust_identifier(&parameter.name, NameStyle::Snake)
                .unwrap_or_else(|| "invalid_parameter".to_owned())
        })
        .collect::<Vec<_>>();
    let tuple = match arguments.as_slice() {
        [] => "()".to_owned(),
        [argument] => format!("({argument},)"),
        _ => format!("({})", arguments.join(", ")),
    };
    let call = if callable.asyncness.is_async() {
        format!(
            "self.authority.call_async::<{}, _>(&{}, {tuple}).await",
            generated.return_type, generated.constant_name
        )
    } else {
        format!(
            "self.authority.call::<{}, _>(&{}, {tuple})",
            generated.return_type, generated.constant_name
        )
    };
    if callable.asyncness.is_async() {
        writeln!(
            output,
            "            pub async fn {}(&mut self, {}) -> ::vela_engine::binding::VmResult<{}> {{ {call} }}",
            generated.rust_name, parameters, generated.return_type
        )
        .expect("writing to String");
    } else {
        writeln!(
            output,
            "            pub fn {}(&mut self, {}) -> ::vela_engine::binding::VmResult<{}> {{ {call} }}",
            generated.rust_name, parameters, generated.return_type
        )
        .expect("writing to String");
    }
}

fn render_type(
    ty: &RustBindingType,
    source: Span,
    diagnostics: &mut Vec<RustBindingDiagnostic>,
) -> String {
    match ty {
        RustBindingType::Any => "::vela_engine::runtime::VelaValue".to_owned(),
        RustBindingType::Path {
            segments,
            arguments,
        } => {
            let Some(last) = segments.last() else {
                diagnostics.push(RustBindingDiagnostic {
                    code: "bindgen::empty_type_path",
                    message: "an exported Vela type has an empty path".to_owned(),
                    source: Some(source),
                });
                return "()".to_owned();
            };
            let rendered_arguments = arguments
                .iter()
                .map(|argument| render_type(argument, source, diagnostics))
                .collect::<Vec<_>>();
            match (last.as_str(), rendered_arguments.as_slice()) {
                ("Unit", []) => "()".to_owned(),
                ("Bytes", []) => "::std::vec::Vec<u8>".to_owned(),
                ("Array", [item]) => format!("::std::vec::Vec<{item}>"),
                ("Map", [key, value]) => {
                    format!("::std::collections::BTreeMap<{key}, {value}>")
                }
                ("Set", [item]) => format!("::std::collections::BTreeSet<{item}>"),
                ("Option", [item]) => format!("::std::option::Option<{item}>"),
                ("Result", [ok, error]) => {
                    format!("::std::result::Result<{ok}, {error}>")
                }
                ("Iterator", _) => {
                    diagnostics.push(RustBindingDiagnostic {
                        code: "bindgen::unsupported_iterator_boundary",
                        message: "Iterator cannot cross a generated Rust binding boundary"
                            .to_owned(),
                        source: Some(source),
                    });
                    "()".to_owned()
                }
                (primitive, [])
                    if matches!(
                        primitive,
                        "bool"
                            | "char"
                            | "i8"
                            | "i16"
                            | "i32"
                            | "i64"
                            | "i128"
                            | "isize"
                            | "u8"
                            | "u16"
                            | "u32"
                            | "u64"
                            | "u128"
                            | "usize"
                            | "f32"
                            | "f64"
                            | "String"
                    ) =>
                {
                    primitive.to_owned()
                }
                _ => {
                    let path = segments
                        .iter()
                        .filter_map(|segment| rust_identifier(segment, NameStyle::Preserve))
                        .collect::<Vec<_>>()
                        .join("::");
                    if rendered_arguments.is_empty() {
                        format!("crate::{path}")
                    } else {
                        format!("crate::{path}<{}>", rendered_arguments.join(", "))
                    }
                }
            }
        }
    }
}

#[derive(Clone, Copy)]
enum NameStyle {
    Preserve,
    Snake,
}

fn rust_identifier(value: &str, style: NameStyle) -> Option<String> {
    let mut identifier = String::new();
    let mut previous_underscore = false;
    for (index, character) in value.chars().enumerate() {
        let valid = character == '_' || character.is_ascii_alphanumeric();
        let character = if valid { character } else { '_' };
        if character == '_' && previous_underscore {
            continue;
        }
        if index == 0 && character.is_ascii_digit() {
            identifier.push('_');
        }
        identifier.push(match style {
            NameStyle::Preserve => character,
            NameStyle::Snake => character.to_ascii_lowercase(),
        });
        previous_underscore = character == '_';
    }
    let identifier = identifier.trim_matches('_');
    if identifier.is_empty() {
        return None;
    }
    if rust_keywords().contains(identifier) {
        Some(format!("r#{identifier}"))
    } else {
        Some(identifier.to_owned())
    }
}

fn plain_identifier(identifier: &str) -> &str {
    identifier.strip_prefix("r#").unwrap_or(identifier)
}

fn rust_keywords() -> &'static BTreeSet<&'static str> {
    static KEYWORDS: std::sync::OnceLock<BTreeSet<&'static str>> = std::sync::OnceLock::new();
    KEYWORDS.get_or_init(|| {
        [
            "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum",
            "extern", "false", "final", "fn", "for", "gen", "if", "impl", "in", "let", "loop",
            "macro", "match", "mod", "move", "mut", "override", "priv", "pub", "ref", "return",
            "self", "Self", "static", "struct", "super", "trait", "true", "try", "type", "typeof",
            "union", "unsafe", "unsized", "use", "virtual", "where", "while", "yield",
        ]
        .into_iter()
        .collect()
    })
}

fn generation_error(diagnostic: RustBindingDiagnostic) -> RustBindingGenerationError {
    RustBindingGenerationError {
        diagnostics: Box::new([diagnostic]),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use vela_engine::engine::Engine;

    fn schema(source: &str) -> std::sync::Arc<RustBindingSchema> {
        let engine = Engine::builder().build().expect("test engine");
        engine
            .compile_source(source)
            .expect("test source")
            .binding_schema()
            .clone()
    }

    #[test]
    fn generation_is_deterministic_and_syntactically_valid() {
        let schema = schema(
            r#"
#[doc("Adds two values.")]
pub fn add(left: i64, right: i64 = 1) -> i64 { return left + right; }
pub async fn names(values: Array<String>) -> Result<String, String> { return "ok"; }
"#,
        );
        let options = RustBindingGeneratorOptions::default();
        let first = generate_rust_bindings(&schema, &options).expect("first bindings");
        let second = generate_rust_bindings(&schema, &options).expect("second bindings");

        assert_eq!(first, second);
        assert_eq!(first.schema_checksum, schema.checksum());
        syn::parse_file(&first.code).expect("generated bindings must parse as Rust");
        assert!(first.code.contains("pub fn add"));
        assert!(first.code.contains("pub async fn names"));
        assert!(first.code.contains("Adds two values."));
        assert!(first.code.contains(&format!("{:016x}", schema.checksum())));
    }

    #[test]
    fn generation_uses_schema_only_and_rejects_unsupported_iterator_boundaries() {
        let schema =
            schema("pub fn consume(values: Iterator<i64>) -> i64 { return values.count(); }");
        let error = generate_rust_bindings(&schema, &RustBindingGeneratorOptions::default())
            .expect_err("iterator boundary should fail");

        assert!(error.diagnostics().iter().any(|diagnostic| {
            diagnostic.code == "bindgen::unsupported_iterator_boundary"
                && diagnostic.source.is_some()
        }));
    }
}
