use std::collections::{BTreeMap, BTreeSet};
use std::fmt::{self, Write};

use vela_bytecode::{
    RUST_BINDING_SCHEMA_VERSION, RustBindingBoundaryMode, RustBindingCallable,
    RustBindingCallableIdentity, RustBindingModule, RustBindingSchema, RustBindingType,
    RustBindingTypeDefinition, RustBindingVariantFields,
};
use vela_common::Span;

#[derive(Clone, Debug)]
pub struct RustBindingsBuilder<'schema> {
    schema: &'schema RustBindingSchema,
    module_name: String,
}

impl<'schema> RustBindingsBuilder<'schema> {
    #[must_use]
    pub fn new(schema: &'schema RustBindingSchema) -> Self {
        Self {
            schema,
            module_name: "vela_bindings".to_owned(),
        }
    }

    #[must_use]
    pub fn module_name(mut self, module_name: impl Into<String>) -> Self {
        self.module_name = module_name.into();
        self
    }

    pub fn generate(self) -> Result<GeneratedRustBindings, RustBindingGenerationError> {
        generate_rust_bindings(self.schema, &self.module_name)
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedRustBindings {
    pub code: String,
    pub schema_version: u32,
    pub schema_checksum: u64,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RustBindingDiagnostic {
    pub code: &'static str,
    pub message: String,
    pub source: Option<Span>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RustBindingGenerationError {
    diagnostics: Box<[RustBindingDiagnostic]>,
}

impl RustBindingGenerationError {
    #[must_use]
    pub fn diagnostics(&self) -> &[RustBindingDiagnostic] {
        &self.diagnostics
    }
}

impl fmt::Display for RustBindingGenerationError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "Rust binding generation failed with {} diagnostic(s)",
            self.diagnostics.len()
        )
    }
}

impl std::error::Error for RustBindingGenerationError {}

fn generate_rust_bindings(
    schema: &RustBindingSchema,
    module_name: &str,
) -> Result<GeneratedRustBindings, RustBindingGenerationError> {
    let mut diagnostics = Vec::new();
    if schema.version() != RUST_BINDING_SCHEMA_VERSION {
        diagnostics.push(RustBindingDiagnostic {
            code: "bindgen::unsupported_schema_version",
            message: format!(
                "binding schema version {} is not supported; expected {}",
                schema.version(),
                RUST_BINDING_SCHEMA_VERSION
            ),
            source: None,
        });
    }
    let module_name = rust_identifier(module_name, NameStyle::Snake).ok_or_else(|| {
        generation_error(RustBindingDiagnostic {
            code: "bindgen::invalid_module_name",
            message: format!("`{}` cannot be represented as a Rust module", module_name),
            source: None,
        })
    })?;
    let modules = collect_modules(schema, &mut diagnostics);
    validate_types(schema, &mut diagnostics);
    if !diagnostics.is_empty() {
        return Err(RustBindingGenerationError {
            diagnostics: diagnostics.into_boxed_slice(),
        });
    }

    let mut code = String::new();
    writeln!(code, "// @generated by vela_bindgen; do not edit.").expect("writing to String");
    writeln!(
        code,
        "// Vela binding schema v{} checksum {:016x}.",
        schema.version(),
        schema.checksum()
    )
    .expect("writing to String");
    writeln!(
        code,
        "#[allow(clippy::all, dead_code, non_camel_case_types)]"
    )
    .expect("writing to String");
    writeln!(code, "pub mod {module_name} {{").expect("writing to String");
    writeln!(
        code,
        "    pub const SCHEMA_VERSION: u32 = {};",
        schema.version()
    )
    .expect("writing to String");
    writeln!(
        code,
        "    pub const SCHEMA_CHECKSUM: u64 = 0x{:016x};",
        schema.checksum()
    )
    .expect("writing to String");
    writeln!(
        code,
        "    fn conversion_error(expected: &'static str) -> ::vela_engine::binding::VmError {{"
    )
    .expect("writing to String");
    writeln!(code, "        ::vela_engine::binding::VmError::new(::vela_engine::binding::VmErrorKind::TypeContractViolation {{ expected: expected.to_owned(), actual: \"incompatible generated binding value\".to_owned(), debug_name: expected.to_owned() }})").expect("writing to String");
    writeln!(code, "    }}").expect("writing to String");
    render_specs(&mut code, &modules, schema);
    render_types(&mut code, schema);
    render_package(&mut code, &modules);
    for module in &modules {
        render_module(&mut code, module);
    }
    writeln!(code, "}}").expect("writing to String");

    Ok(GeneratedRustBindings {
        code,
        schema_version: schema.version(),
        schema_checksum: schema.checksum(),
    })
}

fn validate_types(schema: &RustBindingSchema, diagnostics: &mut Vec<RustBindingDiagnostic>) {
    let mut generated_names = BTreeMap::<String, (&str, Span)>::new();
    for definition in schema.types() {
        let (public_path, source) = match definition {
            RustBindingTypeDefinition::Record(record) => {
                for field in &record.fields {
                    let _ = render_type(&field.ty, field.source, diagnostics);
                }
                (&record.public_path, record.source)
            }
            RustBindingTypeDefinition::Enum(item) => {
                for variant in &item.variants {
                    match &variant.fields {
                        RustBindingVariantFields::Unit => {}
                        RustBindingVariantFields::Tuple(fields) => {
                            for field in fields {
                                let _ = render_type(field, variant.source, diagnostics);
                            }
                        }
                        RustBindingVariantFields::Record(fields) => {
                            for field in fields {
                                let _ = render_type(&field.ty, field.source, diagnostics);
                            }
                        }
                    }
                }
                (&item.public_path, item.source)
            }
        };
        let name = generated_type_name(public_path);
        if name.is_empty() {
            diagnostics.push(RustBindingDiagnostic {
                code: "bindgen::invalid_type_name",
                message: format!(
                    "Vela type `{public_path}` cannot be represented as a generated Rust type"
                ),
                source: Some(source),
            });
            continue;
        }
        if let Some((other_path, _)) = generated_names.insert(name.clone(), (public_path, source)) {
            diagnostics.push(RustBindingDiagnostic {
                code: "bindgen::type_name_collision",
                message: format!(
                    "Vela types `{other_path}` and `{public_path}` both map to generated Rust type `{name}`"
                ),
                source: Some(source),
            });
        }
    }
}

struct GeneratedModule<'schema> {
    rust_name: String,
    accessor_name: String,
    source_name: String,
    callables: Vec<GeneratedCallable<'schema>>,
}

struct GeneratedCallable<'schema> {
    schema_index: usize,
    constant_name: String,
    rust_name: String,
    callable: &'schema RustBindingCallable,
    parameter_types: Vec<String>,
    return_type: String,
}

fn collect_modules<'schema>(
    schema: &'schema RustBindingSchema,
    diagnostics: &mut Vec<RustBindingDiagnostic>,
) -> Vec<GeneratedModule<'schema>> {
    let mut modules = Vec::new();
    let mut module_names = BTreeSet::new();
    for package in schema.packages() {
        for module in &package.modules {
            let source_name = module_source_name(package.id.as_str(), module);
            let Some(rust_name) = rust_identifier(&source_name, NameStyle::Snake) else {
                diagnostics.push(RustBindingDiagnostic {
                    code: "bindgen::invalid_module_path",
                    message: format!("`{source_name}` cannot be represented as a Rust module"),
                    source: module.callables.first().map(|callable| callable.source),
                });
                continue;
            };
            if !module_names.insert(rust_name.clone()) {
                diagnostics.push(RustBindingDiagnostic {
                    code: "bindgen::module_name_collision",
                    message: format!(
                        "Vela module `{source_name}` collides with another generated Rust module `{rust_name}`"
                    ),
                    source: module.callables.first().map(|callable| callable.source),
                });
                continue;
            }
            let mut method_names = BTreeSet::new();
            let mut callables = Vec::new();
            for (index, callable) in module.callables.iter().enumerate() {
                let Some(callable_name) = rust_identifier(&callable.rust_name, NameStyle::Snake)
                else {
                    diagnostics.push(RustBindingDiagnostic {
                        code: "bindgen::invalid_callable_name",
                        message: format!(
                            "Vela callable `{}` cannot be represented as a Rust method",
                            callable.public_path
                        ),
                        source: Some(callable.source),
                    });
                    continue;
                };
                if !method_names.insert(callable_name.clone()) {
                    diagnostics.push(RustBindingDiagnostic {
                        code: "bindgen::callable_name_collision",
                        message: format!(
                            "Vela callable `{}` collides with generated Rust method `{callable_name}`",
                            callable.public_path
                        ),
                        source: Some(callable.source),
                    });
                    continue;
                }
                let parameter_types = callable
                    .parameters
                    .iter()
                    .map(|parameter| {
                        render_parameter_type(
                            &parameter.ty,
                            parameter.mode,
                            parameter.source,
                            diagnostics,
                        )
                    })
                    .collect::<Vec<_>>();
                let return_type = render_type(&callable.returns.ty, callable.source, diagnostics);
                callables.push(GeneratedCallable {
                    schema_index: 0,
                    constant_name: format!(
                        "CALLABLE_{}_{index}",
                        plain_identifier(&callable_name).to_ascii_uppercase()
                    ),
                    rust_name: callable_name,
                    callable,
                    parameter_types,
                    return_type,
                });
            }
            modules.push(GeneratedModule {
                accessor_name: format!("{rust_name}_module"),
                rust_name,
                source_name,
                callables,
            });
        }
    }
    modules.sort_by(|left, right| left.source_name.cmp(&right.source_name));
    for (schema_index, callable) in modules
        .iter_mut()
        .flat_map(|module| module.callables.iter_mut())
        .enumerate()
    {
        callable.schema_index = schema_index;
    }
    modules
}

fn module_source_name(package: &str, module: &RustBindingModule) -> String {
    let package = if package.is_empty() || package == "<anonymous>" {
        "anonymous"
    } else {
        package
    };
    let path = module.path.join();
    if path.is_empty() {
        format!("{package}_root")
    } else {
        format!("{package}_{path}")
    }
}

fn render_specs(output: &mut String, modules: &[GeneratedModule<'_>], schema: &RustBindingSchema) {
    writeln!(
        output,
        "    pub static SCHEMA: ::vela_engine::binding::BindingSchemaSpec = ::vela_engine::binding::BindingSchemaSpec::new(SCHEMA_VERSION, SCHEMA_CHECKSUM, &[")
    .expect("writing to String");
    for module in modules {
        for generated in &module.callables {
            let callable = generated.callable;
            let constructor = match callable.identity {
                RustBindingCallableIdentity::Function(function) => format!(
                    "::vela_engine::binding::BindingCallableSpec::function({:?}, 0x{:032x}, 0x{:032x}, 0x{:016x}, {}, {}, {}, {})",
                    callable.public_path,
                    function.get(),
                    callable.executable.get(),
                    callable.contract_fingerprint,
                    callable.effects.bits(),
                    callable.source.source.get(),
                    callable.source.start,
                    callable.source.end
                ),
                RustBindingCallableIdentity::Method { owner, method } => format!(
                    "::vela_engine::binding::BindingCallableSpec::method({:?}, 0x{:032x}, 0x{:032x}, 0x{:032x}, 0x{:016x}, {}, {}, {}, {})",
                    callable.public_path,
                    owner.get(),
                    method.get(),
                    callable.executable.get(),
                    callable.contract_fingerprint,
                    callable.effects.bits(),
                    callable.source.source.get(),
                    callable.source.start,
                    callable.source.end
                ),
            };
            writeln!(output, "        {constructor},").expect("writing to String");
        }
    }
    writeln!(output, "    ]).with_types(&[").expect("writing to String");
    for package in schema.packages() {
        for module in &package.modules {
            for definition in &module.types {
                let (path, id, fingerprint, source) = match definition {
                    RustBindingTypeDefinition::Record(record) => (
                        &record.public_path,
                        record.type_id,
                        record.schema_fingerprint,
                        record.source,
                    ),
                    RustBindingTypeDefinition::Enum(item) => (
                        &item.public_path,
                        item.type_id,
                        item.schema_fingerprint,
                        item.source,
                    ),
                };
                writeln!(
                    output,
                    "        ::vela_engine::binding::BindingTypeSpec::new({path:?}, 0x{:032x}, 0x{fingerprint:016x}, {}, {}, {}),",
                    id.get(), source.source.get(), source.start, source.end
                )
                .expect("writing to String");
            }
        }
    }
    writeln!(output, "    ]);").expect("writing to String");
}

fn render_types(output: &mut String, schema: &RustBindingSchema) {
    writeln!(output, "    pub mod types {{").expect("writing to String");
    for definition in schema
        .packages()
        .iter()
        .flat_map(|package| &package.modules)
        .flat_map(|module| &module.types)
    {
        match definition {
            RustBindingTypeDefinition::Record(record) => render_record(output, record),
            RustBindingTypeDefinition::Enum(item) => render_enum(output, item),
        }
    }
    writeln!(output, "    }}").expect("writing to String");
}

fn render_record(output: &mut String, record: &vela_bytecode::RustBindingRecord) {
    let name = generated_type_name(&record.public_path);
    writeln!(output, "        #[derive(Clone, Debug, PartialEq)]").expect("writing to String");
    writeln!(output, "        pub struct {name} {{").expect("writing to String");
    for field in &record.fields {
        let field_name = rust_identifier(&field.name, NameStyle::Snake)
            .unwrap_or_else(|| "invalid_field".to_owned());
        let ty = render_type(&field.ty, field.source, &mut Vec::new());
        writeln!(output, "            pub {field_name}: {ty},").expect("writing to String");
    }
    writeln!(output, "        }}").expect("writing to String");
    writeln!(
        output,
        "        impl ::vela_engine::args::IntoScriptArg for {name} {{"
    )
    .expect("writing to String");
    writeln!(
        output,
        "            fn into_script_arg(self) -> ::vela_engine::binding::OwnedValue {{"
    )
    .expect("writing to String");
    writeln!(
        output,
        "                ::vela_engine::binding::OwnedValue::record({:?}, [",
        record.public_path
    )
    .expect("writing to String");
    for field in &record.fields {
        let field_name = rust_identifier(&field.name, NameStyle::Snake)
            .unwrap_or_else(|| "invalid_field".to_owned());
        writeln!(output, "                    ({:?}, ::vela_engine::args::IntoScriptArg::into_script_arg(self.{field_name})),", field.name).expect("writing to String");
    }
    writeln!(output, "                ])").expect("writing to String");
    writeln!(output, "            }}").expect("writing to String");
    writeln!(output, "        }}").expect("writing to String");
    render_record_from_value(output, record, &name);
}

fn render_record_from_value(
    output: &mut String,
    record: &vela_bytecode::RustBindingRecord,
    name: &str,
) {
    writeln!(
        output,
        "        impl ::vela_engine::args::FromScriptArg for {name} {{"
    )
    .expect("writing to String");
    writeln!(
        output,
        "            const TYPE_NAME: &'static str = {:?};",
        record.public_path
    )
    .expect("writing to String");
    writeln!(output, "            fn from_script_arg(value: &::vela_engine::binding::OwnedValue) -> ::vela_engine::binding::VmResult<Self> {{").expect("writing to String");
    writeln!(output, "                let ::vela_engine::binding::OwnedValue::Record {{ type_name, fields }} = value else {{ return Err(super::conversion_error(Self::TYPE_NAME)); }};").expect("writing to String");
    writeln!(output, "                if type_name != {:?} {{ return Err(super::conversion_error(Self::TYPE_NAME)); }}", record.public_path).expect("writing to String");
    writeln!(output, "                if fields.len() != {} {{ return Err(super::conversion_error(Self::TYPE_NAME)); }}", record.fields.len()).expect("writing to String");
    writeln!(output, "                Ok(Self {{").expect("writing to String");
    for field in &record.fields {
        let field_name = rust_identifier(&field.name, NameStyle::Snake)
            .unwrap_or_else(|| "invalid_field".to_owned());
        let ty = render_type(&field.ty, field.source, &mut Vec::new());
        writeln!(output, "                    {field_name}: <{ty} as ::vela_engine::args::FromScriptArg>::from_script_arg(fields.get({:?}).ok_or_else(|| super::conversion_error(Self::TYPE_NAME))?)?,", field.name).expect("writing to String");
    }
    writeln!(output, "                }})").expect("writing to String");
    writeln!(output, "            }}").expect("writing to String");
    writeln!(output, "        }}").expect("writing to String");
}

fn render_enum(output: &mut String, item: &vela_bytecode::RustBindingEnum) {
    let name = generated_type_name(&item.public_path);
    writeln!(output, "        #[derive(Clone, Debug, PartialEq)]").expect("writing to String");
    writeln!(output, "        pub enum {name} {{").expect("writing to String");
    for variant in &item.variants {
        let variant_name = rust_identifier(&variant.name, NameStyle::Preserve)
            .unwrap_or_else(|| "InvalidVariant".to_owned());
        match &variant.fields {
            RustBindingVariantFields::Unit => {
                writeln!(output, "            {variant_name},").expect("writing to String");
            }
            RustBindingVariantFields::Tuple(fields) => {
                let fields = fields
                    .iter()
                    .map(|field| render_type(field, variant.source, &mut Vec::new()))
                    .collect::<Vec<_>>()
                    .join(", ");
                writeln!(output, "            {variant_name}({fields}),")
                    .expect("writing to String");
            }
            RustBindingVariantFields::Record(fields) => {
                writeln!(output, "            {variant_name} {{").expect("writing to String");
                for field in fields {
                    let field_name = rust_identifier(&field.name, NameStyle::Snake)
                        .unwrap_or_else(|| "invalid_field".to_owned());
                    let ty = render_type(&field.ty, field.source, &mut Vec::new());
                    writeln!(output, "                {field_name}: {ty},")
                        .expect("writing to String");
                }
                writeln!(output, "            }},").expect("writing to String");
            }
        }
    }
    writeln!(output, "        }}").expect("writing to String");
    render_enum_into_value(output, item, &name);
    render_enum_from_value(output, item, &name);
}

fn render_enum_into_value(output: &mut String, item: &vela_bytecode::RustBindingEnum, name: &str) {
    writeln!(
        output,
        "        impl ::vela_engine::args::IntoScriptArg for {name} {{"
    )
    .expect("writing to String");
    writeln!(
        output,
        "            fn into_script_arg(self) -> ::vela_engine::binding::OwnedValue {{"
    )
    .expect("writing to String");
    writeln!(output, "                match self {{").expect("writing to String");
    for variant in &item.variants {
        let variant_name = rust_identifier(&variant.name, NameStyle::Preserve)
            .unwrap_or_else(|| "InvalidVariant".to_owned());
        match &variant.fields {
            RustBindingVariantFields::Unit => {
                writeln!(output, "                    Self::{variant_name} => ::vela_engine::binding::OwnedValue::enum_variant({:?}, {:?}, [] as [(&str, ::vela_engine::binding::OwnedValue); 0]),", item.public_path, variant.name).expect("writing to String");
            }
            RustBindingVariantFields::Tuple(fields) => {
                let bindings = (0..fields.len())
                    .map(|index| format!("field_{index}"))
                    .collect::<Vec<_>>();
                writeln!(output, "                    Self::{variant_name}({}) => ::vela_engine::binding::OwnedValue::enum_variant({:?}, {:?}, [", bindings.join(", "), item.public_path, variant.name).expect("writing to String");
                for (index, binding) in bindings.iter().enumerate() {
                    writeln!(output, "                        ({:?}, ::vela_engine::args::IntoScriptArg::into_script_arg({binding})),", index.to_string()).expect("writing to String");
                }
                writeln!(output, "                    ]),").expect("writing to String");
            }
            RustBindingVariantFields::Record(fields) => {
                let bindings = fields
                    .iter()
                    .map(|field| {
                        rust_identifier(&field.name, NameStyle::Snake)
                            .unwrap_or_else(|| "invalid_field".to_owned())
                    })
                    .collect::<Vec<_>>();
                writeln!(output, "                    Self::{variant_name} {{ {} }} => ::vela_engine::binding::OwnedValue::enum_variant({:?}, {:?}, [", bindings.join(", "), item.public_path, variant.name).expect("writing to String");
                for (field, binding) in fields.iter().zip(&bindings) {
                    writeln!(output, "                        ({:?}, ::vela_engine::args::IntoScriptArg::into_script_arg({binding})),", field.name).expect("writing to String");
                }
                writeln!(output, "                    ]),").expect("writing to String");
            }
        }
    }
    writeln!(output, "                }}").expect("writing to String");
    writeln!(output, "            }}").expect("writing to String");
    writeln!(output, "        }}").expect("writing to String");
}

fn render_enum_from_value(output: &mut String, item: &vela_bytecode::RustBindingEnum, name: &str) {
    writeln!(
        output,
        "        impl ::vela_engine::args::FromScriptArg for {name} {{"
    )
    .expect("writing to String");
    writeln!(
        output,
        "            const TYPE_NAME: &'static str = {:?};",
        item.public_path
    )
    .expect("writing to String");
    writeln!(output, "            fn from_script_arg(value: &::vela_engine::binding::OwnedValue) -> ::vela_engine::binding::VmResult<Self> {{").expect("writing to String");
    writeln!(output, "                let ::vela_engine::binding::OwnedValue::Enum {{ enum_name, variant, fields }} = value else {{ return Err(super::conversion_error(Self::TYPE_NAME)); }};").expect("writing to String");
    writeln!(output, "                if enum_name != {:?} {{ return Err(super::conversion_error(Self::TYPE_NAME)); }}", item.public_path).expect("writing to String");
    writeln!(output, "                match variant.as_str() {{").expect("writing to String");
    for variant in &item.variants {
        let variant_name = rust_identifier(&variant.name, NameStyle::Preserve)
            .unwrap_or_else(|| "InvalidVariant".to_owned());
        match &variant.fields {
            RustBindingVariantFields::Unit => {
                writeln!(
                    output,
                    "                    {:?} if fields.is_empty() => Ok(Self::{variant_name}),",
                    variant.name
                )
                .expect("writing to String");
            }
            RustBindingVariantFields::Tuple(field_types) => {
                writeln!(
                    output,
                    "                    {:?} if fields.len() == {} => Ok(Self::{variant_name}(",
                    variant.name,
                    field_types.len()
                )
                .expect("writing to String");
                for (index, ty) in field_types.iter().enumerate() {
                    let ty = render_type(ty, variant.source, &mut Vec::new());
                    writeln!(output, "                        <{ty} as ::vela_engine::args::FromScriptArg>::from_script_arg(fields.get({:?}).ok_or_else(|| super::conversion_error(Self::TYPE_NAME))?)?,", index.to_string()).expect("writing to String");
                }
                writeln!(output, "                    )),").expect("writing to String");
            }
            RustBindingVariantFields::Record(field_types) => {
                writeln!(
                    output,
                    "                    {:?} if fields.len() == {} => Ok(Self::{variant_name} {{",
                    variant.name,
                    field_types.len()
                )
                .expect("writing to String");
                for field in field_types {
                    let field_name = rust_identifier(&field.name, NameStyle::Snake)
                        .unwrap_or_else(|| "invalid_field".to_owned());
                    let ty = render_type(&field.ty, field.source, &mut Vec::new());
                    writeln!(output, "                        {field_name}: <{ty} as ::vela_engine::args::FromScriptArg>::from_script_arg(fields.get({:?}).ok_or_else(|| super::conversion_error(Self::TYPE_NAME))?)?,", field.name).expect("writing to String");
                }
                writeln!(output, "                    }}),").expect("writing to String");
            }
        }
    }
    writeln!(
        output,
        "                    _ => Err(super::conversion_error(Self::TYPE_NAME)),"
    )
    .expect("writing to String");
    writeln!(output, "                }}").expect("writing to String");
    writeln!(output, "            }}").expect("writing to String");
    writeln!(output, "        }}").expect("writing to String");
}

fn render_package(output: &mut String, modules: &[GeneratedModule<'_>]) {
    writeln!(output, "    pub struct Package<A> {{ authority: A }}").expect("writing to String");
    writeln!(
        output,
        "    pub fn bind(runtime: &mut ::vela_engine::runtime::Runtime) -> ::vela_engine::binding::BindingResult<Package<::vela_engine::binding::RootBinding<'_>>> {{"
    )
    .expect("writing to String");
    writeln!(
        output,
        "        Ok(Package {{ authority: ::vela_engine::binding::RootBinding::bind(runtime, &SCHEMA)? }})"
    )
    .expect("writing to String");
    writeln!(output, "    }}").expect("writing to String");
    writeln!(
        output,
        "    pub fn bind_active<'binding, 'context, 'host>(context: &'binding mut ::vela_engine::context::NativeCallContext<'context, 'host>) -> ::vela_engine::binding::BindingResult<Package<::vela_engine::binding::ActiveBinding<'binding, 'context, 'host>>> {{"
    )
    .expect("writing to String");
    writeln!(
        output,
        "        Ok(Package {{ authority: ::vela_engine::binding::ActiveBinding::bind(context, &SCHEMA)? }})"
    )
    .expect("writing to String");
    writeln!(output, "    }}").expect("writing to String");
    writeln!(
        output,
        "    impl<A: ::vela_engine::binding::BindingAuthority> Package<A> {{"
    )
    .expect("writing to String");
    for module in modules {
        writeln!(
            output,
            "        pub fn {}(&mut self) -> {}::Module<'_, A> {{ {}::Module {{ authority: &mut self.authority }} }}",
            module.accessor_name, module.rust_name, module.rust_name
        )
        .expect("writing to String");
    }
    writeln!(output, "    }}").expect("writing to String");
}

fn render_module(output: &mut String, module: &GeneratedModule<'_>) {
    writeln!(output, "    pub mod {} {{", module.rust_name).expect("writing to String");
    writeln!(
        output,
        "        pub struct Module<'a, A> {{ pub(super) authority: &'a mut A }}"
    )
    .expect("writing to String");
    for generated in &module.callables {
        writeln!(
            output,
            "        const {}: ::vela_engine::binding::BindingCallable = ::vela_engine::binding::BindingCallable::new(&super::SCHEMA, {});",
            generated.constant_name, generated.schema_index
        )
        .expect("writing to String");
    }
    writeln!(
        output,
        "        impl<'a, A: ::vela_engine::binding::BindingAuthority> Module<'a, A> {{"
    )
    .expect("writing to String");
    for generated in &module.callables {
        render_callable(output, generated);
    }
    writeln!(output, "        }}").expect("writing to String");
    writeln!(output, "    }}").expect("writing to String");
}

fn render_callable(output: &mut String, generated: &GeneratedCallable<'_>) {
    let callable = generated.callable;
    if let Some(docs) = &callable.docs {
        for line in docs.lines() {
            writeln!(output, "            #[doc = {:?}]", line).expect("writing to String");
        }
    }
    writeln!(
        output,
        "            #[doc = {:?}]",
        format!(
            "Vela source {}:{}..{}; contract {:016x}.",
            callable.source.source.get(),
            callable.source.start,
            callable.source.end,
            callable.contract_fingerprint
        )
    )
    .expect("writing to String");
    let parameters = generated
        .parameter_types
        .iter()
        .zip(&callable.parameters)
        .enumerate()
        .map(|(index, (ty, parameter))| {
            let name = if index == 0 && callable.owner.is_some() && parameter.name == "self" {
                "receiver".to_owned()
            } else {
                rust_identifier(&parameter.name, NameStyle::Snake)
                    .unwrap_or_else(|| "invalid_parameter".to_owned())
            };
            format!("{name}: {ty}")
        })
        .collect::<Vec<_>>()
        .join(", ");
    let arguments = callable
        .parameters
        .iter()
        .enumerate()
        .map(|(index, parameter)| {
            if index == 0 && callable.owner.is_some() && parameter.name == "self" {
                "receiver".to_owned()
            } else {
                rust_identifier(&parameter.name, NameStyle::Snake)
                    .unwrap_or_else(|| "invalid_parameter".to_owned())
            }
        })
        .collect::<Vec<_>>();
    let has_host_parameters = callable
        .parameters
        .iter()
        .any(|parameter| parameter.mode != RustBindingBoundaryMode::Value);
    let tuple = match arguments.as_slice() {
        [] => "()".to_owned(),
        [argument] => format!("({argument},)"),
        _ => format!("({})", arguments.join(", ")),
    };
    let call = if callable.asyncness.is_async() && has_host_parameters {
        let mut prepared =
            String::from("let mut __vela_args = ::vela_engine::runtime::CallArgs::new(); ");
        for (parameter, argument) in callable.parameters.iter().zip(&arguments) {
            match parameter.mode {
                RustBindingBoundaryMode::Value => {
                    write!(prepared, "__vela_args.push_value({:?}, ::vela_engine::args::IntoScriptArg::into_script_arg({argument})); ", parameter.name).expect("writing to String");
                }
                RustBindingBoundaryMode::SharedHost => {
                    write!(
                        prepared,
                        "self.authority.push_host_ref(&mut __vela_args, {:?}, {argument})?; ",
                        parameter.name
                    )
                    .expect("writing to String");
                }
                RustBindingBoundaryMode::ExclusiveHost => {
                    write!(
                        prepared,
                        "self.authority.push_host_mut(&mut __vela_args, {:?}, {argument})?; ",
                        parameter.name
                    )
                    .expect("writing to String");
                }
            }
        }
        format!(
            "{prepared}self.authority.call_prepared_async::<{}>(&{}, __vela_args).await",
            generated.return_type, generated.constant_name
        )
    } else if callable.asyncness.is_async() {
        format!(
            "self.authority.call_async::<{}, _>(&{}, {tuple}).await",
            generated.return_type, generated.constant_name
        )
    } else if has_host_parameters {
        let mut prepared =
            String::from("let mut __vela_args = ::vela_engine::runtime::CallArgs::new(); ");
        for (parameter, argument) in callable.parameters.iter().zip(&arguments) {
            match parameter.mode {
                RustBindingBoundaryMode::Value => {
                    write!(prepared, "__vela_args.push_value({:?}, ::vela_engine::args::IntoScriptArg::into_script_arg({argument})); ", parameter.name).expect("writing to String");
                }
                RustBindingBoundaryMode::SharedHost => {
                    write!(
                        prepared,
                        "self.authority.push_host_ref(&mut __vela_args, {:?}, {argument})?; ",
                        parameter.name
                    )
                    .expect("writing to String");
                }
                RustBindingBoundaryMode::ExclusiveHost => {
                    write!(
                        prepared,
                        "self.authority.push_host_mut(&mut __vela_args, {:?}, {argument})?; ",
                        parameter.name
                    )
                    .expect("writing to String");
                }
            }
        }
        format!(
            "{prepared}self.authority.call_prepared::<{}>(&{}, __vela_args)",
            generated.return_type, generated.constant_name
        )
    } else {
        format!(
            "self.authority.call::<{}, _>(&{}, {tuple})",
            generated.return_type, generated.constant_name
        )
    };
    if callable.asyncness.is_async() {
        writeln!(
            output,
            "            pub async fn {}(&mut self, {}) -> ::vela_engine::binding::VmResult<{}> {{ {call} }}",
            generated.rust_name, parameters, generated.return_type
        )
        .expect("writing to String");
    } else {
        writeln!(
            output,
            "            pub fn {}(&mut self, {}) -> ::vela_engine::binding::VmResult<{}> {{ {call} }}",
            generated.rust_name, parameters, generated.return_type
        )
        .expect("writing to String");
    }
}

fn render_type(
    ty: &RustBindingType,
    source: Span,
    diagnostics: &mut Vec<RustBindingDiagnostic>,
) -> String {
    match ty {
        RustBindingType::Any => {
            diagnostics.push(RustBindingDiagnostic {
                code: "bindgen::untyped_boundary",
                message: "a generated typed Rust binding requires an explicit Vela type hint"
                    .to_owned(),
                source: Some(source),
            });
            "()".to_owned()
        }
        RustBindingType::Host { public_path, .. } => render_external_type_path(public_path),
        RustBindingType::Definition { public_path, .. } => {
            format!("super::types::{}", generated_type_name(public_path))
        }
        RustBindingType::Path {
            segments,
            arguments,
        } => {
            let Some(last) = segments.last() else {
                diagnostics.push(RustBindingDiagnostic {
                    code: "bindgen::empty_type_path",
                    message: "an exported Vela type has an empty path".to_owned(),
                    source: Some(source),
                });
                return "()".to_owned();
            };
            let rendered_arguments = arguments
                .iter()
                .map(|argument| render_type(argument, source, diagnostics))
                .collect::<Vec<_>>();
            match (last.as_str(), rendered_arguments.as_slice()) {
                ("Unit", []) => "()".to_owned(),
                ("Bytes", []) => "::std::vec::Vec<u8>".to_owned(),
                ("Array", [item]) => format!("::std::vec::Vec<{item}>"),
                ("Map", [key, value]) => {
                    format!("::std::collections::BTreeMap<{key}, {value}>")
                }
                ("Set", [item]) => format!("::std::collections::BTreeSet<{item}>"),
                ("Option", [item]) => format!("::std::option::Option<{item}>"),
                ("Result", [ok, error]) => {
                    format!("::std::result::Result<{ok}, {error}>")
                }
                ("Iterator", _) => {
                    diagnostics.push(RustBindingDiagnostic {
                        code: "bindgen::unsupported_iterator_boundary",
                        message: "Iterator cannot cross a generated Rust binding boundary"
                            .to_owned(),
                        source: Some(source),
                    });
                    "()".to_owned()
                }
                (primitive, [])
                    if matches!(
                        primitive,
                        "bool"
                            | "char"
                            | "i8"
                            | "i16"
                            | "i32"
                            | "i64"
                            | "i128"
                            | "isize"
                            | "u8"
                            | "u16"
                            | "u32"
                            | "u64"
                            | "u128"
                            | "usize"
                            | "f32"
                            | "f64"
                            | "String"
                    ) =>
                {
                    primitive.to_owned()
                }
                _ => {
                    let path = segments
                        .iter()
                        .filter_map(|segment| rust_identifier(segment, NameStyle::Preserve))
                        .collect::<Vec<_>>()
                        .join("::");
                    if rendered_arguments.is_empty() {
                        format!("crate::{path}")
                    } else {
                        format!("crate::{path}<{}>", rendered_arguments.join(", "))
                    }
                }
            }
        }
    }
}

fn generated_type_name(public_path: &str) -> String {
    public_path
        .split("::")
        .filter_map(|segment| rust_identifier(segment, NameStyle::Preserve))
        .map(|segment| {
            let mut characters = plain_identifier(&segment).chars();
            characters.next().map_or_else(String::new, |first| {
                first.to_ascii_uppercase().to_string() + characters.as_str()
            })
        })
        .collect::<String>()
}

fn render_parameter_type(
    ty: &RustBindingType,
    mode: RustBindingBoundaryMode,
    source: Span,
    diagnostics: &mut Vec<RustBindingDiagnostic>,
) -> String {
    if let RustBindingType::Host { public_path, .. } = ty {
        let ty = render_external_type_path(public_path);
        return match mode {
            RustBindingBoundaryMode::SharedHost => format!("&{ty}"),
            RustBindingBoundaryMode::ExclusiveHost => format!("&mut {ty}"),
            RustBindingBoundaryMode::Value => {
                diagnostics.push(RustBindingDiagnostic {
                    code: "bindgen::invalid_host_boundary_mode",
                    message: format!(
                        "host type `{public_path}` requires a shared or exclusive reference mode"
                    ),
                    source: Some(source),
                });
                ty
            }
        };
    }
    match ty {
        RustBindingType::Path {
            segments,
            arguments,
        } if arguments.is_empty() && segments.last().is_some_and(|last| last == "String") => {
            "&str".to_owned()
        }
        RustBindingType::Path {
            segments,
            arguments,
        } if arguments.is_empty() && segments.last().is_some_and(|last| last == "Bytes") => {
            "&[u8]".to_owned()
        }
        _ => render_type(ty, source, diagnostics),
    }
}

fn render_external_type_path(public_path: &str) -> String {
    let path = public_path
        .split("::")
        .filter_map(|segment| rust_identifier(segment, NameStyle::Preserve))
        .collect::<Vec<_>>()
        .join("::");
    format!("crate::{path}")
}

#[derive(Clone, Copy)]
enum NameStyle {
    Preserve,
    Snake,
}

fn rust_identifier(value: &str, style: NameStyle) -> Option<String> {
    let mut identifier = String::new();
    let mut previous_underscore = false;
    for (index, character) in value.chars().enumerate() {
        let valid = character == '_' || character.is_ascii_alphanumeric();
        let character = if valid { character } else { '_' };
        if character == '_' && previous_underscore {
            continue;
        }
        if index == 0 && character.is_ascii_digit() {
            identifier.push('_');
        }
        identifier.push(match style {
            NameStyle::Preserve => character,
            NameStyle::Snake => character.to_ascii_lowercase(),
        });
        previous_underscore = character == '_';
    }
    let identifier = identifier.trim_matches('_');
    if identifier.is_empty() {
        return None;
    }
    if rust_keywords().contains(identifier) {
        Some(format!("r#{identifier}"))
    } else {
        Some(identifier.to_owned())
    }
}

fn plain_identifier(identifier: &str) -> &str {
    identifier.strip_prefix("r#").unwrap_or(identifier)
}

fn rust_keywords() -> &'static BTreeSet<&'static str> {
    static KEYWORDS: std::sync::OnceLock<BTreeSet<&'static str>> = std::sync::OnceLock::new();
    KEYWORDS.get_or_init(|| {
        [
            "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum",
            "extern", "false", "final", "fn", "for", "gen", "if", "impl", "in", "let", "loop",
            "macro", "match", "mod", "move", "mut", "override", "priv", "pub", "ref", "return",
            "self", "Self", "static", "struct", "super", "trait", "true", "try", "type", "typeof",
            "union", "unsafe", "unsized", "use", "virtual", "where", "while", "yield",
        ]
        .into_iter()
        .collect()
    })
}

fn generation_error(diagnostic: RustBindingDiagnostic) -> RustBindingGenerationError {
    RustBindingGenerationError {
        diagnostics: Box::new([diagnostic]),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use vela_engine::engine::Engine;

    fn schema(source: &str) -> std::sync::Arc<RustBindingSchema> {
        let engine = Engine::builder().build().expect("test engine");
        engine
            .compile_source(source)
            .expect("test source")
            .binding_schema()
            .clone()
    }

    #[test]
    fn generation_is_deterministic_and_syntactically_valid() {
        let schema = schema(
            r#"
#[doc("Adds two values.")]
pub fn add(left: i64, right: i64 = 1) -> i64 { return left + right; }
pub async fn names(values: Array<String>) -> Result<String, String> { return "ok"; }
"#,
        );
        let first = RustBindingsBuilder::new(&schema)
            .generate()
            .expect("first bindings");
        let second = RustBindingsBuilder::new(&schema)
            .generate()
            .expect("second bindings");

        assert_eq!(first, second);
        assert_eq!(first.schema_checksum, schema.checksum());
        syn::parse_file(&first.code).expect("generated bindings must parse as Rust");
        assert!(first.code.contains("pub fn add"));
        assert!(first.code.contains("pub async fn names"));
        assert!(first.code.contains("Adds two values."));
        assert!(first.code.contains(&format!("{:016x}", schema.checksum())));

        let named = RustBindingsBuilder::new(&schema)
            .module_name("game_api")
            .generate()
            .expect("named bindings");
        assert!(named.code.contains("pub mod game_api"));
    }

    #[test]
    fn generation_uses_schema_only_and_rejects_unsupported_iterator_boundaries() {
        let schema =
            schema("pub fn consume(values: Iterator<i64>) -> i64 { return values.count(); }");
        let error = RustBindingsBuilder::new(&schema)
            .generate()
            .expect_err("iterator boundary should fail");

        assert!(error.diagnostics().iter().any(|diagnostic| {
            diagnostic.code == "bindgen::unsupported_iterator_boundary"
                && diagnostic.source.is_some()
        }));
    }

    #[test]
    fn generation_emits_owned_models_and_typed_method_receivers() {
        let schema = schema(
            r#"
pub struct Point { x: i64, y: i64 }
pub enum Choice { None, One(value: i64), Named { value: i64 } }
pub fn choose(value: Choice) -> Point { return Point { x: 1, y: 2 }; }
impl Point { pub fn sum(self) -> i64 { return self.x + self.y; } }
"#,
        );
        let generated = RustBindingsBuilder::new(&schema)
            .generate()
            .expect("model bindings");

        syn::parse_file(&generated.code).expect("generated models must parse as Rust");
        assert!(generated.code.contains("pub struct Point"));
        assert!(generated.code.contains("pub enum Choice"));
        assert!(
            generated
                .code
                .contains("pub fn sum(&mut self, receiver: super::types::Point)")
        );
        assert!(generated.code.contains("if fields.len() != 2"));
        assert!(generated.code.contains("\"Named\" if fields.len() == 1"));
    }

    #[test]
    fn generation_reports_unsupported_nested_model_fields_at_their_source() {
        let schema = schema(
            r#"
pub struct Stream { values: Iterator<i64> }
pub fn echo(value: Stream) -> Stream { return value; }
"#,
        );
        let error = RustBindingsBuilder::new(&schema)
            .generate()
            .expect_err("nested iterator boundary should fail");

        assert!(error.diagnostics().iter().any(|diagnostic| {
            diagnostic.code == "bindgen::unsupported_iterator_boundary"
                && diagnostic.source.is_some()
        }));
    }
}
