[package]
name = "vela_cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap = { workspace = true }
vela_bytecode = { workspace = true }
vela_common = { workspace = true }
vela_engine = { workspace = true }
vela_language_service = { workspace = true }
vela_vm = { workspace = true }

[dev-dependencies]
vela_host = { workspace = true }
vela_macros = { workspace = true }

[lints]
workspace = true
